---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: fusion-app-http-container
    service: fusion-ui
    team: cdf-ux
  name: fusion
  namespace: apps
spec:
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: fusion-dev
    weight: 100
status: null
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"http":"fusion-dev-backend-config"},
      "default" : "fusion-dev-backend-config"}'
    strategy.spinnaker.io/use-source-capacity: "true"
  labels:
    app: fusion-app-http-container
    service: fusion-ui
    team: cdf-ux
  name: fusion-dev
  namespace: apps
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: fusion-dev
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    strategy.spinnaker.io/use-source-capacity: "true"
  labels:
    app: fusion-app-http-container
    service: fusion-ui
    team: cdf-ux
  name: fusion-dev
  namespace: apps
spec:
  minReadySeconds: 0
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: fusion-dev
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: fusion-dev
        service: fusion-ui
        team: cdf-ux
    spec:
      containers:
      - image: eu.gcr.io/cognitedata/fusion-app
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 5
        name: fusion-dev
        ports:
        - containerPort: 8000
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 8000
        resources:
          limits:
            cpu: 400m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 128Mi
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/default.conf
          name: nginx-config
          subPath: nginx.config
      volumes:
      - configMap:
          name: nginx-config-file-map
        name: nginx-config
---
apiVersion: v1
data:
  nginx.config: |+
    server {
       listen 8000;

       add_header Access-Control-Allow-Origin *;

       root /usr/share/nginx/html;
       server_tokens off;
       gzip on;
       gzip_types text/plain text/css text/xml application/xml application/javascript application/json image/svg+xml;
       gzip_comp_level 5;
       gzip_proxied any;
       gzip_vary on;

       location / {
         try_files $uri /index.html;
         add_header X-Frame-Options SAMEORIGIN always;
         add_header Cache-Control "max-age=300, stale-while-revalidate=600";
         add_header Strict-Transport-Security "max-age=63072000; includeSubdomains";
         add_header X-Content-Type-Options nosniff;
       }

       location ~ /subapps-import-map.json$ {
         try_files /subapps-import-map-staging.json =404;
       }

       location ~ /assets/.+\.(js|png|jpg|jpeg|map|svg|css|woff2)$ {
         expires max;
       }

       location ~ /dependencies/.+\.(js|png|jpg|jpeg|map|svg)$ {
         expires max;
       }

       location ~ \.(js|png|jpg|jpeg|map|svg)$ {
         add_header Cache-Control "max-age=300, stale-while-revalidate=3600";
       }
    }

kind: ConfigMap
metadata:
  labels:
    app: fusion-app-http-container
    service: fusion-ui
    team: cdf-ux
  name: nginx-config-file-map
  namespace: apps
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: fusion-app-http-container
    service: fusion-ui
    team: cdf-ux
  name: fusion-dev
  namespace: apps
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fusion-dev
