//Explorer action types
export const GENERATE_NODE_TREE = "GENERATE_NODE_TREE";
export const CHANGE_SELECTED_TAB = "CHANGE_SELECTED_TAB";

export const TOGGLE_NODE_SELECT = "TOGGLE_NODE_SELECT";
export const TOGGLE_NODE_EXPAND = "TOGGLE_NODE_EXPAND";

export const TOGGLE_NODE_CHECK = "TOGGLE_NODE_CHECK";
export const TOGGLE_NODE_CHECK_SUCCESS = "TOGGLE_NODE_CHECK_SUCCESS";

export const CHANGE_CHECKBOX_STATE = "CHANGE_CHECKBOX_STATE";