// Action type constants
export const TOGGLE_NODE_VISIBILITY = "TOGGLE_NODE_VISIBILITY";
export const TOGGLE_NODE_SELECTION = "TOGGLE_NODE_SELECTION";
export const FETCH_DOMAIN_NODES = "FETCH_DOMAIN_NODES";
