// Action type constants
export const ON_INPUT_CHANGE = "ON_INPUT_CHANGE";
export const ON_EXPAND_CHANGE = "ON_EXPAND_CHANGE";
export const ON_EXPAND_CHANGE_FROM_TOOLBAR = "ON_EXPAND_CHANGE_FROM_TOOLBAR";
export const ON_CHANGE_SETTING_AVAILABILITY = "ON_CHANGE_SETTING_AVAILABILITY";
