// Visualizer Toolbar action types
export const SET_VISUALIZER_TOOLBARS = "SET_VISUALIZER_TOOLBARS";
export const EXECUTE_VISUALIZER_TOOLBAR_COMMAND = "EXECUTE_VISUALIZER_TOOLBAR_COMMAND";
export const EXECUTE_VISUALIZER_TOOLBAR_COMMAND_SUCCESS = "EXECUTE_VISUALIZER_TOOLBAR_COMMAND_SUCCESS";