// Visualizer Toolbar action types
export const SET_VISUALIZER_DATA = "SET_VISUALIZER_DATA";
export const EXECUTE_VISUALIZER_TOOLBAR_COMMAND = "EXECUTE_VISUALIZER_TOOLBAR_COMMAND";
export const EXECUTE_VISUALIZER_TOOLBAR_COMMAND_SUCCESS = "EXECUTE_VISUALIZER_TOOLBAR_COMMAND_SUCCESS";
