// Visualizer Toolbar action types
export const SET_VISUALIZER_DATA = "SET_VISUALIZER_DATA";
export const SET_STATUS_PANEL_TEXT = "SET_STATUS_PANEL_TEXT";
export const EXECUTE_VISUALIZER_TOOLBAR_COMMAND = "EXECUTE_VISUALIZER_TOOLBAR_COMMAND";
export const EXECUTE_VISUALIZER_TOOLBAR_COMMAND_SUCCESS = "EXECUTE_VISUALIZER_TOOLBAR_COMMAND_SUCCESS";
export const UPDATE_TOOLBARS = "UPDATE_TOOLBAR";

