// common
export const SET_FULLSCREEN_STATUS = "SET_FULLSCREEN_STATUS";

// explorer

export const GENERATE_NODE_TREE = "GENERATE_NODE_TREE";
export const CHANGE_SELECTED_TAB = "CHANGE_SELECTED_TAB";
export const CHANGE_CHECKBOX_STATE = "CHANGE_CHECKBOX_STATE";
export const CHANGE_SELECT_STATE = "CHANGE_SELECT_STATE";
export const CHANGE_EXPAND_STATE = "CHANGE_EXPAND_STATE";
export const CHANGE_ACTIVE_STATE = "CHANGE_ACTIVE_STATE";
export const CHANGE_NODE_NAME = "CHANGE_NODE_NAME";
export const CHANGE_NODE_COLOR = "CHANGE_NODE_COLOR";

// visualizers

// Visualizer Toolbar action types
export const SET_VISUALIZER_DATA = "SET_VISUALIZER_DATA";
export const SET_STATUS_PANEL_TEXT = "SET_STATUS_PANEL_TEXT";
export const EXECUTE_VISUALIZER_TOOLBAR_COMMAND = "EXECUTE_VISUALIZER_TOOLBAR_COMMAND";
export const EXECUTE_VISUALIZER_TOOLBAR_COMMAND_SUCCESS = "EXECUTE_VISUALIZER_TOOLBAR_COMMAND_SUCCESS";
export const UPDATE_TOOLBARS = "UPDATE_TOOLBAR";
export const SELECT_ON_CHANGE = "SELECT_ON_CHANGE";
