// common
export const SET_FULLSCREEN_STATUS = "SET_FULLSCREEN_STATUS";

// explorer

export const GENERATE_NODE_TREE = "GENERATE_NODE_TREE";
export const CHANGE_SELECTED_TAB = "CHANGE_SELECTED_TAB";

export const TOGGLE_NODE_SELECT = "TOGGLE_NODE_SELECT";
export const TOGGLE_NODE_EXPAND = "TOGGLE_NODE_EXPAND";

export const TOGGLE_NODE_CHECK = "TOGGLE_NODE_CHECK";
export const TOGGLE_NODE_CHECK_SUCCESS = "TOGGLE_NODE_CHECK_SUCCESS";

export const CHANGE_CHECKBOX_STATE = "CHANGE_CHECKBOX_STATE";
export const CHANGE_SELECT_STATE = "CHANGE_SELECT_STATE";
export const CHANGE_ACTIVE_STATE = "CHANGE_ACTIVE_STATE";
export const CHANGE_NODE_NAME = "CHANGE_NODE_NAME";
export const CHANGE_NODE_COLOR = "CHANGE_NODE_COLOR";

// settings

export const ON_SELECTED_NODE_CHANGE = "ON_SELECTED_NODE_CHANGE";
export const ON_INPUT_CHANGE = "ON_INPUT_CHANGE";
export const ON_EXPAND_CHANGE = "ON_EXPAND_CHANGE";
export const ON_EXPAND_CHANGE_FROM_TOOLBAR = "ON_EXPAND_CHANGE_FROM_TOOLBAR";
export const ON_CHANGE_SETTING_AVAILABILITY = "ON_CHANGE_SETTING_AVAILABILITY";
export const CHANGE_SETTINGS_PROPERTY = "CHANGED_SETTINGS_PROPERTY";

// visualizers

// Visualizer Toolbar action types
export const SET_VISUALIZER_DATA = "SET_VISUALIZER_DATA";
export const SET_STATUS_PANEL_TEXT = "SET_STATUS_PANEL_TEXT";
export const EXECUTE_VISUALIZER_TOOLBAR_COMMAND = "EXECUTE_VISUALIZER_TOOLBAR_COMMAND";
export const EXECUTE_VISUALIZER_TOOLBAR_COMMAND_SUCCESS = "EXECUTE_VISUALIZER_TOOLBAR_COMMAND_SUCCESS";
export const UPDATE_TOOLBARS = "UPDATE_TOOLBAR";
export const SELECT_ON_CHANGE = "SELECT_ON_CHANGE";
