export const POLLING_INTERVAL = 5000; // in ms
export const LABELING_TABLE_COLUMN_WIDTH = 220;
export const NUM_MANUAL_MATCHES_TO_STATISTICALLY_SIGNIFICANT = 5;
export const MAX_COMPLETED_PERCENTAGE = 100;
