import { mapService } from 'modules/map/service';

import { Layers } from '../types';

const OIL_COLOR = 'rgba(160,203,134, 1)';
const GAS_COLOR = 'rgba(227,140,138,1)';
const CONDENSATE_COLOR = 'rgba(236,193,129, 1)';
const PROSPECT_COLOR = 'rgba(250,237,153, 0.75)';
const WATER_COLOR = 'rgba(105,186,227, 1)';
const UNKNOWN_COLOR = 'rgba(128,128,128, 1)';

const weights: Record<string, number> = [
  'quadrants',
  'blocks',
  'structuralElements',
  'licensesByOperators',
  'licenses',
  'idemitsuLicenses',
  'fields',
  'discoveries',
  'prospects',
  'pipelines',
  'facilities',
  'idemitsuWellTrajectories',
  'idemitsuWellHeads',
].reduce((result, key, index) => {
  return {
    ...result,
    [key]: index + 1000,
  };
}, {});

const ipnDevLayers = {
  explorationWellsActive: {
    remoteService: mapService.getWellboresExplorationActive,
    name: 'Exploration Wells Active',
    color: 'black',
    defaultOn: false,
    mapLayers: [
      {
        id: 'explorationWellsActive',
        source: 'explorationWellsActive',
        type: 'circle',
        minzoom: 6,
        paint: {
          'circle-color': '#222',
          'circle-radius': 2,
          'circle-blur': 0.1,
          'circle-stroke-color': '#eee',
        },
        weight: weights.idemitsuWellHeads,
      },
      {
        id: 'explorationWellsActiveLabel',
        source: 'explorationWellsActive',
        type: 'symbol',
        minzoom: 7,
        layout: {
          'text-field': '{name}',
          'text-font': ['Open Sans Semibold', 'Arial Unicode MS Bold'],
          'text-size': 12,
          'text-offset': [0, 1],
        },
        weight: weights.idemitsuWellHeads + 1,
      },
    ],
  },
  idemitsuWellTrajectories: {
    // remoteService: mapService.getTrajectories,
    name: 'Selected Trajectories',
    color: 'red',
    defaultOn: false,
    mapLayers: [
      {
        id: 'idemitsuWellTrajectories',
        minzoom: 6,
        source: 'idemitsuWellTrajectories',
        type: 'line',
        layout: {},
        paint: {
          'line-color': 'red',
        },
        weight: weights.idemitsuWellTrajectories,
      },
      {
        id: 'ntLabel',
        source: 'idemitsuWellTrajectories',
        type: 'symbol',
        minzoom: 7,
        layout: {
          'text-field': '{name}',
          'text-font': ['Open Sans Semibold', 'Arial Unicode MS Bold'],
          'text-size': 12,
          'text-anchor': 'top',
          'text-justify': 'center',
          'symbol-placement': 'line',
        },
        weight: weights.idemitsuWellTrajectories + 1,
      },
    ],
  },
  facilities: {
    remoteService: mapService.getFacilities,
    name: 'Facilities',
    color: 'rgba(41,120,255, 1)',
    defaultOn: false,
    mapLayers: [
      {
        id: 'facilities',
        source: 'facilities',
        type: 'symbol',
        layout: {
          'icon-image': [
            'match',
            ['get', 'surface'],
            'Y',
            'surface_facility_icon',
            'N',
            'subsurface_facility_icon',
            'subsurface_facility_icon',
          ],
          'icon-size': 1.1,
          'icon-allow-overlap': true,
        },
        paint: {},
        weight: weights.facilities,
      },
      {
        id: 'facilitiesLabel',
        source: 'facilities',
        type: 'symbol',
        minzoom: 6,
        layout: {
          'text-field': '{name}',
          'text-font': ['Open Sans Semibold', 'Arial Unicode MS Bold'],
          'text-size': 12,
          'text-anchor': 'top',
          'text-justify': 'center',
        },
        weight: weights.facilities + 1,
      },
    ],
  },
  pipelines: {
    remoteService: mapService.getPipelines,
    name: 'Pipelines',
    color: 'green',
    defaultOn: false,
    mapLayers: [
      {
        id: 'pipelines',
        minzoom: 6,
        source: 'pipelines',
        type: 'line',
        layout: {},
        paint: {
          'line-color': [
            'match',
            ['get', 'type'],
            'Oil',
            OIL_COLOR,
            'Gas',
            GAS_COLOR,
            'Condensate',
            CONDENSATE_COLOR,
            'water',
            WATER_COLOR,
            UNKNOWN_COLOR,
          ],
        },
        weight: weights.pipelines,
      },
      {
        id: 'pipelinesLabel',
        source: 'pipelines',
        type: 'symbol',
        minzoom: 7,
        layout: {
          'text-field': '{label}',
          'text-font': ['Open Sans Semibold', 'Arial Unicode MS Bold'],
          'text-size': 12,
          'text-anchor': 'top',
          'text-justify': 'center',
          'symbol-placement': 'line',
        },
        weight: weights.pipelines + 1,
      },
    ],
  },
  prospects: {
    remoteService: mapService.getProspects,
    name: 'Idemitsu Prospects',
    color: PROSPECT_COLOR,
    defaultOn: false,
    mapLayers: [
      {
        id: 'prospects',
        source: 'prospects',
        type: 'fill',
        layout: {},
        paint: {
          'fill-outline-color': '#000',
          'fill-color': PROSPECT_COLOR,
        },
        weight: weights.prospects,
      },
      {
        id: 'prospectsLabel',
        source: 'prospects',
        type: 'symbol',
        minzoom: 6,
        filter: ['!=', 'name', 'None'],
        layout: {
          'text-field': '{name}',
          'text-font': ['Open Sans Semibold', 'Arial Unicode MS Bold'],
          'text-size': 12,
        },
        weight: weights.prospects + 1,
      },
    ],
  },
  discoveries: {
    remoteService: mapService.getDiscoveries,
    name: 'Discoveries',
    color: 'rgba(183, 102, 25, 0.8)',
    defaultOn: false,
    filter: ['==', 'fieldname', 'nan'],
    mapLayers: [
      {
        id: 'discoveries',
        source: 'discoveries',
        type: 'fill',
        layout: {},
        filter: [
          'all',
          ['in', 'dctype', 'OIL', 'GAS'],
          ['==', 'fieldname', 'nan'],
        ],
        paint: {
          'fill-outline-color': '#000',
          'fill-color': [
            'match',
            ['get', 'dctype'],
            'OIL',
            OIL_COLOR,
            'GAS',
            GAS_COLOR,
            UNKNOWN_COLOR,
          ],
        },
        weight: weights.discoveries,
      },
      {
        id: 'complexDiscoveries',
        source: 'discoveries',
        type: 'fill',
        layout: {},
        filter: [
          'all',
          ['in', 'dctype', 'OIL/GAS', 'GAS/CONDENSATE'],
          ['==', 'fieldname', 'nan'],
        ],
        paint: {
          'fill-outline-color': '#000',
          'fill-pattern': [
            'match',
            ['get', 'dctype'],
            'OIL/GAS',
            'oil_gas_pattern',
            'GAS/CONDENSATE',
            'gas_condensate_pattern',
            'oil_gas_pattern',
          ],
        },
        weight: weights.discoveries,
      },
      {
        id: 'discoveriesLabel',
        source: 'discoveries',
        type: 'symbol',
        minzoom: 6,
        filter: ['==', 'fieldname', 'nan'],
        layout: {
          'text-field': '{name}',
          'text-font': ['Open Sans Semibold', 'Arial Unicode MS Bold'],
          'text-size': 12,
        },
        weight: weights.discoveries + 1,
      },
    ],
  },
  Fields: {
    remoteService: mapService.getFields,
    name: 'Fields',
    color: 'rgba(0, 172, 79, 0.8)',
    defaultOn: true,
    asset: {
      filter: [
        'name',
        [
          'BYRDING',
          'DUVA',
          'FRAM',
          'FRAM H-NORD',
          'KNARR',
          'SNORRE',
          'STATFJORD ØST',
          'SYGNA',
          'TORDIS',
          'VEGA',
          'VIGDIS',
        ],
      ],
      displayField: 'name',
    },
    mapLayers: [
      {
        id: 'simpleFields',
        source: 'Fields',
        type: 'fill',
        layout: {},
        filter: ['in', ['get', 'dctype'], ['literal', ['OIL', 'GAS']]],
        paint: {
          'fill-outline-color': '#000',
          'fill-color': [
            'match',
            ['get', 'dctype'],
            'OIL',
            OIL_COLOR,
            'GAS',
            GAS_COLOR,
            UNKNOWN_COLOR,
          ],
        },
        weight: weights.fields,
      },
      {
        id: 'complexFields',
        source: 'Fields',
        type: 'fill',
        layout: {},
        filter: [
          'in',
          ['get', 'dctype'],
          ['literal', ['OIL/GAS', 'GAS/CONDENSATE']],
        ],
        paint: {
          'fill-outline-color': '#000',
          'fill-pattern': [
            'match',
            ['get', 'dctype'],
            'OIL/GAS',
            'oil_gas_pattern',
            'GAS/CONDENSATE',
            'gas_condensate_pattern',
            'oil_gas_pattern',
          ],
        },
        weight: weights.fields,
      },
      {
        id: 'FieldsLabel',
        source: 'Fields',
        type: 'symbol',
        minzoom: 6,
        layout: {
          'text-field': '{name}',
          'text-font': ['Open Sans Semibold', 'Arial Unicode MS Bold'],
          'text-size': 12,
        },
        weight: weights.fields + 1,
      },
    ],
  },
  IdemitsuLicenses: {
    remoteService: mapService.getIdemitsuLicenses,
    name: 'Idemitsu Licenses',
    color: 'rgba(255, 190, 190, 1)',
    defaultOn: false,
    mapLayers: [
      {
        id: 'IdemitsuLicenses',
        source: 'IdemitsuLicenses',
        type: 'fill',
        layout: {},
        paint: {
          'fill-outline-color': 'rgba(0, 0, 0, 1)',
          'fill-color': 'rgba(255, 190, 190, 1)',
        },
        weight: weights.idemitsuLicenses,
      },
      {
        id: 'IdemitsuLicensesLabel',
        source: 'IdemitsuLicenses',
        type: 'symbol',
        minzoom: 8,
        layout: {
          'text-field': '{name}',
          'text-font': ['Open Sans Semibold', 'Arial Unicode MS Bold'],
          'text-size': 12,
        },
        weight: weights.idemitsuLicenses + 1,
      },
    ],
  },
  Licenses: {
    remoteService: mapService.getLicenses,
    name: 'Licenses',
    color: 'rgba(211, 211, 211, 0.6)',
    defaultOn: true,
    mapLayers: [
      {
        id: 'Licenses',
        source: 'Licenses',
        type: 'fill',
        layout: {},
        paint: {
          'fill-outline-color': 'rgba(30, 30, 30, 1)',
          'fill-color': 'rgba(211, 211, 211, 0.6)',
        },
        weight: weights.licenses,
      },
      {
        id: 'LicensesOpLabel',
        source: 'Licenses',
        type: 'symbol',
        minzoom: 8,
        layout: {
          'text-field': '{name}',
          'text-font': ['Open Sans Semibold', 'Arial Unicode MS Bold'],
          'text-size': 12,
        },
        weight: weights.licenses + 1,
      },
    ],
  },
  LicensesByOperators: {
    remoteService: mapService.getLicenses,
    name: 'Licenses by Operator',
    color: 'transparent',
    defaultOn: false,
    mapLayers: [
      {
        id: 'LicensesByOperators',
        source: 'LicensesByOperators',
        type: 'fill',
        layout: {},
        paint: {
          'fill-outline-color': 'rgba(0, 0, 0, 1)',
          'fill-color': [
            'match',
            ['get', 'oplongname'],
            'Wintershall Dea Norge AS',
            'rgba(0, 255, 0, 0.75)',
            'Suncor Energy Norge AS',
            'rgba(255, 0, 0, 0.75)',
            'Wellesley Petroleum AS',
            'rgba(0, 0, 255, 0.75)',
            'DNO Norge AS',
            'rgba(0, 0, 255, 1)',
            'Equinor Energy AS',
            'rgba(248, 148, 6, 0.75)',
            'Lundin Energy Norway AS',
            'rgba(255, 182, 193, 0.75)',
            'Aker BP ASA',
            'rgba(186, 85, 211, 0.75)',
            'Neptune Energy Norge AS',
            'rgba(145, 180, 150, 0.75)',
            'OKEA ASA',
            'rgba(240, 255, 0, 1)',
            'Sval Energi AS',
            'rgba(25, 181, 254, 1)',
            'rgba(0, 106.875, 22.275, 0.5)',
          ],
        },
        weight: weights.licensesByOperators,
      },
      {
        id: 'LicensesByOperatorsOpLabel',
        source: 'LicensesByOperators',
        type: 'symbol',
        minzoom: 8,
        layout: {
          'text-field': '{oplongname}',
          'text-font': ['Open Sans Semibold', 'Arial Unicode MS Bold'],
          'text-size': 12,
        },
        weight: weights.licensesByOperators + 1,
      },
    ],
  },
  structuralElements: {
    remoteService: mapService.getStructuralElements,
    name: 'Structural Elements',
    color: 'transparent',
    defaultOn: false,
    mapLayers: [
      {
        id: 'structuralElements',
        source: 'structuralElements',
        type: 'fill',
        layout: {},
        paint: {
          'fill-color': [
            'match',
            ['get', 'topography'],
            'Cretaceous High',
            '#c8ffca',
            'Deep Cretaceous Basin',
            '#95ca00',
            'Marginal Volcanic High',
            '#ce99ff',
            'Orogenic belt',
            '#f5a37b',
            'Palaeozoic High in Platform',
            '#959595',
            'Platform',
            '#9dcdfa',
            'Pre-Jurassic Basin in Platform',
            '#c3cfdc',
            'Shallow Cretaceous Basin in Platform',
            '#80bdff',
            'Terraces and Intra-Basinal Elevations',
            '#279d64',
            'Volcanics',
            '#cdcef9',
            '#723122',
          ],
          'fill-opacity': 0.75,
        },
        weight: weights.structuralElements,
      },
    ],
  },
  quadrants: {
    remoteService: mapService.getQuadrants,
    name: 'Quadrants',
    color: 'transparent',
    defaultOn: true,
    alwaysOn: true,
    mapLayers: [
      {
        id: 'quadrants',
        maxzoom: 6,
        source: 'quadrants',
        type: 'line',
        layout: {},
        paint: { 'line-color': '#fff', 'line-opacity': 0.8 },
        weight: weights.quadrants,
      },
    ],
  },
} as Layers;

export default ipnDevLayers;
