version: 1
updates:
  - package-ecosystem: npm
    directory: '/'
    allow:
      - dependency-type: 'production'
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    labels:
      - auto-merge
    ignore:
      - dependency-name: antd
        versions:
          - '>= 4.a'
          - '< 5'
      - dependency-name: '@sentry/browser'
        versions:
          - '>= 5'
