version: 2
updates:
- package-ecosystem: npm
  directory: "/examples"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: dependency-updates
  ignore:
  - dependency-name: "@cognite/reveal"
    versions:
    - ">= 0"
  - dependency-name: "@cognite/sdk"
    versions:
    - ">= 0"
  - dependency-name: three
    versions:
    - ">= 0"
- package-ecosystem: npm
  directory: "/viewer"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: dependency-updates
  ignore:
  - dependency-name: husky
    versions:
    - 5.x
- package-ecosystem: cargo
  directory: "/f3df"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: dependency-updates
- package-ecosystem: cargo
  directory: "/i3df"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: dependency-updates
- package-ecosystem: cargo
  directory: "/viewer"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: dependency-updates
