# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  npm-npmjs: # Define access for a private registry
    type: npm-registry
    url: https://registry.npmjs.org
    token: ${{secrets.NPM_DEPENDABOT_READONLY}}

updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    registries:
      - npm-npmjs
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Europe/Oslo"
    labels:
      - "dependencies"
