version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@sentry/browser"
    versions:
    - 6.0.3
    - 6.0.4
    - 6.1.0
    - 6.2.0
    - 6.2.1
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.3.0
    - 6.3.1
    - 6.3.2
    - 6.3.3
  - dependency-name: "@types/node"
    versions:
    - 14.14.41
    - 14.14.5
    - 15.0.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.1.0
    - 8.2.0
    - 8.3.0
  - dependency-name: eslint-plugin-testing-library
    versions:
    - 3.10.2
    - 4.0.0
    - 4.0.1
    - 4.1.0
  - dependency-name: "@types/sinon"
    versions:
    - 10.0.0
  - dependency-name: "@cognite/sdk"
    versions:
    - 3.3.3
    - 3.3.4
    - 3.3.5
    - 3.3.6
    - 3.4.0
    - 4.0.2
  - dependency-name: testcafe
    versions:
    - 1.11.0
    - 1.12.0
    - 1.13.0
    - 1.14.0
  - dependency-name: sinon
    versions:
    - 10.0.0
    - 10.0.1
  - dependency-name: husky
    versions:
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 6.0.0
  - dependency-name: react-dom
    versions:
    - 17.0.1
    - 17.0.2
  - dependency-name: react
    versions:
    - 17.0.2
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
    - 4.0.3
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.10
    - 24.1.4
    - 24.1.5
    - 24.1.6
    - 24.1.7
    - 24.1.8
    - 24.1.9
    - 24.2.0
    - 24.2.1
    - 24.3.0
    - 24.3.1
    - 24.3.2
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: "@types/react"
    versions:
    - 17.0.2
    - 17.0.3
  - dependency-name: redux-devtools-extension
    versions:
    - 2.13.9
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: lodash
    versions:
    - 4.17.21
  - dependency-name: react-use-intercom
    versions:
    - 1.1.9
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.0
    - 17.0.1
  - dependency-name: "@storybook/react"
    versions:
    - 6.1.16
    - 6.1.17
  - dependency-name: "@storybook/addon-docs"
    versions:
    - 6.1.16
    - 6.1.17
  - dependency-name: "@storybook/addon-knobs"
    versions:
    - 6.1.16
    - 6.1.17
  - dependency-name: "@storybook/addon-viewport"
    versions:
    - 6.1.16
    - 6.1.17
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.4
    - 11.2.5
  commit-message:
    prefix: chore
    include: scope
