version: 2
registries:
  npm:
    type: npm-registry
    url: https://registry.npmjs.org
    token: ${{secrets.NPM_READONLY_TOKEN}}
  gcr:
    type: docker-registry
    url: eu.gcr.io
    username: _json_key
    password: ${{secrets.GCR_READONLY_JSON_KEY}}
updates:
  - package-ecosystem: npm
    directory: "/"
    allow:
      - dependency-type: "production"
    schedule:
      interval: weekly
      day: "saturday"
    labels:
      - auto-merge
      - auto-update
    commit-message:
      prefix: chore
      include: scope
    registries:
      - npm
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    labels:
      - auto-merge
      - auto-update
    commit-message:
      prefix: chore
      include: scope
    registries:
      - gcr
