version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore: "
    labels:
      - "auto-update"
      - "auto-merge"
