version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: '@cognite/cogs.js'
        versions:
          - '>= 1.1.a, < 1.2'
      - dependency-name: eslint-plugin-testing-library
        versions:
          - 4.1.1
      - dependency-name: eslint-plugin-jest
        versions:
          - 24.3.5
      - dependency-name: eslint-config-prettier
        versions:
          - 8.0.0
          - 8.1.0
          - 8.2.0
      - dependency-name: concurrently
        versions:
          - 6.0.0
          - 6.0.1
      - dependency-name: '@sentry/browser'
        versions:
          - 6.0.2
          - 6.0.3
          - 6.0.4
          - 6.1.0
          - 6.2.0
          - 6.2.1
          - 6.2.2
          - 6.2.3
          - 6.2.4
      - dependency-name: typescript
        versions:
          - 4.2.2
          - 4.2.3
      - dependency-name: '@storybook/addon-links'
        versions:
          - 6.1.20
      - dependency-name: '@storybook/addon-essentials'
        versions:
          - 6.1.19
      - dependency-name: '@storybook/react'
        versions:
          - 6.1.19
      - dependency-name: react-scripts
        versions:
          - 4.0.2
    commit-message:
      prefix: chore
      include: scope
