version: 2
registries:
  npm:
    type: npm-registry
    url: https://registry.npmjs.org
    token: ${{secrets.NPM_DEPENDABOT_READONLY}}
updates:
  - package-ecosystem: npm
    directory: "/"
    allow:
      - dependency-type: all
    schedule:
      interval: daily
    labels:
      - auto-merge
    commit-message:
      prefix: chore
      include: scope
    registries:
      - npm
