# "version" is the configuration version, currently "1".
version: 1

# "merge" defines how and when pull requests are merged. If the section is
# missing, bulldozer will consider all pull requests and use default settings.
merge:
  # "method" defines the merge method. The available options are "merge",
  # "rebase", and "squash".
  method: squash

  # "options" defines additional options for the individual merge methods.
  options:
    # "squash" options are only used when the merge method is "squash"
    squash:
      # "title" defines how the title of the commit message is created when
      # generating a squash commit. The options are "pull_request_title",
      # "first_commit_title", and "github_default_title". The default is
      # "pull_request_title".
      title: pull_request_title

      # "body" defines how the body of the commit message is created when
      # generating a squash commit. The options are "pull_request_body",
      # "summarize_commits", and "empty_body". The default is "empty_body".
      body: empty_body

  delete_after_merge: true
  whitelist:
    labels: ['auto-merge']
  blacklist:
    labels: ['do-not-merge']

update:
  whitelist:
    labels: ['auto-update']
  blacklist:
    labels: ['do-not-update']
