exclude_files:
  - '.github/workflows/deploy-docs-to-gh-pages.yml'
  - '.github/workflows/deploy_platypus-cli.yml'
  - '.github/workflows/cli_test.yml'
  - '.github/workflows/platypus-e2e-tests.yml'
  - '.github/workflows/deploy_mock-server.yml'
  - '.github/workflows/platypus-cli_pr_preview.yml'
  - '.github/workflows/code_cov_master.yml'
