---
apiVersion: v1
kind: Service
metadata:
  name: power-ops
  labels:
    team: apps
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: power-ops
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: power-ops
  labels:
    app: power-ops
    team: apps
  annotations:
    strategy.spinnaker.io/use-source-capacity: 'true'
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: power-ops
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
      labels:
        app: power-ops
        team: apps
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - image: eu.gcr.io/cognitedata/apps/power-ops
          name: power-ops
          imagePullPolicy: Always
          env:
            - name: URL_PREFIX
              value: power-ops.app.${account}
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 10
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  annotations:
    external-dns.ambassador-service: ambassador-apps.apps
  labels:
    app: power-ops
    team: apps
  name: power-ops
spec:
  acmeProvider:
    authority: none
  ambassador_id: ambassador-apps
  hostname: power-ops.app.${account}.cogniteapp.com
  tlsSecret:
    name: apps-certificate-cogniteapp-com-secret
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  labels:
    app: power-ops
    team: apps
  name: power-ops
spec:
  add_response_headers:
    Strict-Transport-Security: max-age=31536000
  ambassador_id: ambassador-apps
  host: power-ops.app.${account}.cogniteapp.com
  prefix: /
  rewrite: ''
  service: power-ops
  timeout_ms: 30000
