export const HotKeys = {
  select_tool: 'v',
  create_point: 'k',
  create_bounding_box: 'r',
  pan_tool: 'h',
  create_polygon: 'p',
  create_line: 'l',
  move_up_annotation_list: 'up',
  move_down_annotation_list: 'down',
  move_into_annotation_collection: 'ctrl+down, cmd+down',
  move_out_annotation_collection: 'ctrl+up , cmd+up',
  approve_annotation: 'z',
  reject_annotation: 'x',
  delete_annotation: 'del, backspace',
};
