name: E2E Tests

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  test:
    name: Run Testcafe Tests
    runs-on: windows-latest
    env:
      FUSION_BASE_URL: https://next-release.fusion.cognite.com
      TEST_USER_EMAIL: ${{secrets.TESTUSER_EMAIL}}
      TEST_USER_PASSWORD: ${{secrets.TESTUSER_PASSWORD}}
      TESTCAFE_SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}
      ENVIRONMENT: next-release

    steps:
      - name: Check out qa-cdf-extpipe-testframework
        uses: actions/checkout@v2
        with:
          repository: cognitedata/qa-cdf-extpipe-testframework
          token: ${{ secrets.TESTREPO_TOKEN }}

      - name: wait for 10 minutes
        run: Start-Sleep -s 420
        shell: powershell

      - name: Run tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome:headless tests"

    # - name: Send mail
    #   if: always()
    #   uses: dawidd6/action-send-mail@v3
    #   with:
    #     # Required mail server address:
    #     server_address: smtp.gmail.com
    #     # Required mail server port:
    #     server_port: 465
    #     # Authenticate as this user to SMTP server
    #     username: ${{ secrets.UDARA_EMAIL }}
    #     # Authenticate with this password to SMTP server
    #     password: ${{ secrets.UDARA_EMAIL_PWD }}
    #     # Required mail subject:
    #     subject: Github Actions E2E Test Results ${{ github.event.number }}
    #     # Required recipients' addresses:
    #     to: udara.s@creativesoftware.com, udara.sembukuttiarachchi@cognite.com
    #     # Required sender full name (address can be skipped):
    #     from: Ext-Pipe Testcafe
    #     # HTML body of mail message (might be a filename prefixed with file:// to read from)
    #     html_body: file://reports/report.html
    #     contentType: text/html
