---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  annotations:
    external-dns.ambassador-service: ambassador-apps.apps
  labels:
    app: react-demo-app
    team: apps
  name: react-demo-app
spec:
  acmeProvider:
    authority: none
  ambassador_id: ambassador-apps
  hostname: fas-demo.app.staging.${account}.cogniteapp.com
  tlsSecret:
    name: apps-certificate-cogniteapp-com-secret
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  labels:
    app: react-demo-app
    team: apps
  name: react-demo-app
spec:
  add_response_headers:
    Strict-Transport-Security: max-age=31536000
  ambassador_id: ambassador-apps
  host: fas-demo.app.staging.${account}.cogniteapp.com
  prefix: /
  rewrite: ''
  service: react-demo-app
  timeout_ms: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-demo-app
spec:
  template:
    spec:
      containers:
        - image: eu.gcr.io/cognitedata/apps/react-demo-app
          name: react-demo-app
          env:
            - name: URL_PREFIX
              value: fas-demo.app.staging.${account}
