export const DENSITY_AND_NEUTRON = [
  /**
   * density
   */
  'density',
  'api gravity',
  'avg density',
  'bulk density',
  'cement density',
  'density in',
  'density out',
  'filter cake density',
  'fluid density',
  'frame density',
  'gas density',
  'grain density',
  'hydrocarbon density',
  'interval density',
  'matrix density',
  'max density',
  'min density',
  'mineral density',
  'mud density',
  'oil density',
  'partial density',
  'proppant density',
  'reservoir fluid density',
  'specific gravity',
  'water density',
  'electron density',
  'litho density',
  'net reservoir core grain density point match',
  'net reservoir log grain density point match',
  'shale density',
  'critical mud density',
  'equivalent circulating density',
  'fit equivalent mud weight',
  'lot equivalent mud weight',
  'max mud density',
  'mud density in',
  'mud density out',
  'c7plus specific gravity',
  'gas gravity',
  'matrix specific gravity',
  'oil gravity',
  'water gravity',
  'dry gas gravity',
  'wet gas gravity',

  /**
   * neutron porosity
   */
  'neutron porosity',
  'api neutron',
  'epithermal neutron porosity',
  'matrix epithermal neutron porosity',
  'neutron porosity dolomite',
  'neutron porosity limestone',
  'neutron porosity sandstone',
  'thermal neutron porosity',
  'matrix thermal neutron porosity',
];
