import {
  DataElementType,
  DataElementUnit,
  EquipmentElement,
  EquipmentElementConfig,
} from '../types';

export const equipmentElementsConfig: {
  [key in EquipmentElement]: EquipmentElementConfig;
} = {
  [EquipmentElement.ALT_REGISTRATION_NO]: {
    label: 'Alternate Registration No.',
    type: DataElementType.INT,
    unit: null,
    pcmsKey: '',
  },
  [EquipmentElement.ASSET_NO]: {
    label: 'Asset Number',
    type: DataElementType.INT,
    unit: null,
    pcmsKey: '',
  },
  [EquipmentElement.CLASS]: {
    label: 'Class',
    type: DataElementType.STRING,
    unit: null,
    pcmsKey: '',
  },
  [EquipmentElement.COATING_SEQNO]: {
    label: 'Coating',
    type: DataElementType.STRING,
    unit: null,
    pcmsKey: '',
  },
  [EquipmentElement.CODE_STAMP_YN]: {
    label: 'Code Stamped (Y/N)',
    type: DataElementType.BOOLEAN,
    unit: null,
    pcmsKey: '',
  },
  [EquipmentElement.CUI_POTENTIAL_YN]: {
    label: 'CUI Potential',
    type: DataElementType.BOOLEAN,
    unit: null,
    pcmsKey: '',
  },
  [EquipmentElement.EQUIP_TYPE_DESCRIPTION]: {
    label: 'Equipment Description',
    type: DataElementType.STRING,
    unit: null,
    pcmsKey: '',
  },
  [EquipmentElement.DESIGN_PRESSURE]: {
    label: 'Design Pressure',
    type: DataElementType.INT,
    unit: DataElementUnit.PSI,
    pcmsKey: '',
  },
  [EquipmentElement.DESIGN_TEMP]: {
    label: 'Design Temperature',
    type: DataElementType.INT,
    unit: DataElementUnit.FAHRENHEIT,
    pcmsKey: '',
  },
  [EquipmentElement.ENVIRONMENT_SEQNO]: {
    label: 'Environment',
    unit: null,
    pcmsKey: '',
  },
  [EquipmentElement.EQUIP_HEIGHT]: {
    label: 'Equipment Height',
    type: DataElementType.FLOAT,
    unit: DataElementUnit.FEET,
    pcmsKey: '',
  },
  [EquipmentElement.EQUIP_LENGTH]: {
    label: 'Equipment Length',
    type: DataElementType.FLOAT,
    unit: DataElementUnit.FEET,
    pcmsKey: '',
  },
  [EquipmentElement.EQUIP_ID]: {
    label: 'Equipment ID',
    type: DataElementType.STRING,
    unit: null,
    pcmsKey: '',
  },
  [EquipmentElement.EQUIP_TYPE]: {
    label: 'Equipment Type',
    type: DataElementType.STRING,
    unit: null,
    pcmsKey: '',
  },
  [EquipmentElement.EQUIP_WIDTH]: {
    label: 'Equipment Width',
    type: DataElementType.FLOAT,
    unit: DataElementUnit.FEET,
    pcmsKey: '',
  },
  [EquipmentElement.FIREPROOFING_YN]: {
    label: 'Fireproofing',
    type: DataElementType.BOOLEAN,
    unit: null,
    pcmsKey: '',
  },
  [EquipmentElement.FULL_VACUUM_YN]: {
    label: 'Full Vacuum',
    type: DataElementType.BOOLEAN,
    unit: null,
    pcmsKey: '',
  },
  [EquipmentElement.GOVERNING_CODE]: {
    label: 'Governing Code',
    type: DataElementType.STRING,
    unit: null,
    pcmsKey: '',
  },
  [EquipmentElement.HF_ACID_SERVICE_SEQNO]: {
    label: 'HF Acid Service',
    type: DataElementType.BOOLEAN,
    unit: null,
    pcmsKey: '',
  },
  [EquipmentElement.HEAT_TRACING_YN]: {
    label: 'Heat Tracing',
    type: DataElementType.BOOLEAN,
    unit: null,
    pcmsKey: '',
  },
  [EquipmentElement.IN_SERVICE_DT]: {
    label: 'In Service Date',
    type: DataElementType.DATE,
    unit: null,
    pcmsKey: '',
  },
  [EquipmentElement.INSTALL_DT]: {
    label: 'Install Date',
    type: DataElementType.DATE,
    unit: null,
    pcmsKey: '',
  },
  [EquipmentElement.INSULATION_TYPE_SEQNO]: {
    label: 'Insulation Type',
    unit: null,
    pcmsKey: '',
  },
  [EquipmentElement.MATERIAL]: {
    label: 'General Material',
    unit: null,
    pcmsKey: '',
  },
  [EquipmentElement.MAX_ALLOW_WRK_PRES]: {
    label: 'Max allowable work pressure',
    type: DataElementType.INT,
    unit: DataElementUnit.PSI,
    pcmsKey: '',
  },
  [EquipmentElement.MAX_ALLOW_WRK_TEMP]: {
    label: 'Max allowable work temperature',
    type: DataElementType.INT,
    unit: DataElementUnit.FAHRENHEIT,
    pcmsKey: '',
  },
  [EquipmentElement.MDM_TEMP]: {
    label: 'Min. Design Metal Temp',
    type: DataElementType.INT,
    unit: DataElementUnit.FAHRENHEIT,
    pcmsKey: '',
  },
  [EquipmentElement.OPERATING_PRESSURE]: {
    label: 'Operating Pressure',
    type: DataElementType.INT,
    unit: DataElementUnit.PSI,
    pcmsKey: '',
  },
  [EquipmentElement.OPERATING_STATUS]: {
    label: 'Operating Status',
    type: DataElementType.STRING,
    unit: null,
    pcmsKey: '',
  },
  [EquipmentElement.OPERATING_TEMP]: {
    label: 'Operating Temperature',
    type: DataElementType.INT,
    unit: DataElementUnit.FAHRENHEIT,
    pcmsKey: '',
  },
  [EquipmentElement.ORIENTATION]: {
    label: 'Orientation',
    type: DataElementType.ORIENTATION,
    pcmsKey: '',
  },
  [EquipmentElement.OUTER_DIAMETER]: {
    label: 'Outer Diameter',
    type: DataElementType.FLOAT,
    unit: DataElementUnit.FEET,
    pcmsKey: '',
  },
  [EquipmentElement.MANUFACTURER]: {
    label: 'Manufacturer',
    type: DataElementType.STRING,
    unit: null,
    pcmsKey: '',
  },
  [EquipmentElement.P_ID_DRAWING_NO]: {
    label: 'P - ID Drawing No.',
    type: DataElementType.STRING,
    unit: null,
    pcmsKey: '',
  },
  [EquipmentElement.PROCESS_IMPACT_SEQNO]: {
    label: 'Process Impact',
    unit: null,
    pcmsKey: '',
  },
  [EquipmentElement.PWHT_YN]: {
    label: 'Post Weld Heat Treatment',
    type: DataElementType.BOOLEAN,
    unit: null,
    pcmsKey: '',
  },
  [EquipmentElement.REGISTRATION_NO]: {
    label: 'Registration No.',
    type: DataElementType.INT,
    unit: null,
    pcmsKey: '',
  },
  [EquipmentElement.RERATED_YN]: {
    label: 'Rerated',
    type: DataElementType.BOOLEAN,
    unit: null,
    pcmsKey: '',
  },
  [EquipmentElement.SERVICE]: {
    label: 'Process Service',
    unit: null,
    pcmsKey: '',
  },
  [EquipmentElement.SYSTEM]: {
    label: 'System',
    type: DataElementType.STRING,
    unit: null,
    pcmsKey: '',
  },
  [EquipmentElement.U1_ON_FILE_YN]: {
    label: 'U1 On File?',
    type: DataElementType.BOOLEAN,
    unit: null,
    pcmsKey: '',
  },
  [EquipmentElement.UNIT]: {
    label: 'Unit ID',
    type: DataElementType.STRING,
    unit: null,
    pcmsKey: '',
  },
};

export const equipmentElementsPriorityConfig = [
  EquipmentElement.UNIT,
  EquipmentElement.EQUIP_ID,
  EquipmentElement.EQUIP_TYPE_DESCRIPTION,
  EquipmentElement.EQUIP_TYPE,
  EquipmentElement.IN_SERVICE_DT,
  EquipmentElement.OPERATING_STATUS,
  EquipmentElement.ASSET_NO,
  EquipmentElement.GOVERNING_CODE,
  EquipmentElement.REGISTRATION_NO,
  EquipmentElement.ALT_REGISTRATION_NO,
  EquipmentElement.U1_ON_FILE_YN,
  EquipmentElement.MANUFACTURER,
  EquipmentElement.P_ID_DRAWING_NO,
  EquipmentElement.INSTALL_DT,
  EquipmentElement.CODE_STAMP_YN,
  EquipmentElement.EQUIP_LENGTH,
  EquipmentElement.EQUIP_WIDTH,
  EquipmentElement.EQUIP_HEIGHT,
  EquipmentElement.MAX_ALLOW_WRK_TEMP,
  EquipmentElement.MAX_ALLOW_WRK_PRES,
  EquipmentElement.MDM_TEMP,
  EquipmentElement.DESIGN_TEMP,
  EquipmentElement.DESIGN_PRESSURE,
  EquipmentElement.PWHT_YN,
  EquipmentElement.SYSTEM,
  EquipmentElement.CLASS,
  EquipmentElement.CUI_POTENTIAL_YN,
  EquipmentElement.SERVICE,
  EquipmentElement.OPERATING_TEMP,
  EquipmentElement.OPERATING_PRESSURE,
  EquipmentElement.PROCESS_IMPACT_SEQNO,
  EquipmentElement.MATERIAL,
  EquipmentElement.INSULATION_TYPE_SEQNO,
  EquipmentElement.COATING_SEQNO,
  EquipmentElement.ORIENTATION,
  EquipmentElement.OUTER_DIAMETER,
  EquipmentElement.FIREPROOFING_YN,
  EquipmentElement.HEAT_TRACING_YN,
  EquipmentElement.ENVIRONMENT_SEQNO,
  EquipmentElement.RERATED_YN,
  EquipmentElement.FULL_VACUUM_YN,
  EquipmentElement.HF_ACID_SERVICE_SEQNO,
];
