export const VIEW_MODES = ['Wells', 'Curves'];
export const PRESSURE_UNITS = ['PPG', 'PSI', 'SG'];
export const MEASUREMENTS_REFERENCES = ['MD', 'TVD'];
export const DEFAULT_PRESSURE_UNIT = PRESSURE_UNITS[0];
export const DEFAULT_MEASUREMENTS_REFERENCE = MEASUREMENTS_REFERENCES[0];
