/**
 * Generated by @openapi-codegen
 *
 * @version v1 alpha
 */
import type * as Schemas from './dataQualitySchemas';

export type ErrorResponse = {
  error: Schemas.Error;
};

export type DataSourceListResponse = {
  items: Schemas.DataSourceDto[];
};

export type DataSourceListResponseWithCursor = {
  items: Schemas.DataSourceDto[];
  nextCursor?: Schemas.NextCursorV3;
};

export type DataSourceListIdsResponse = {
  /**
   * @minItems 1
   * @maxItems 100
   */
  items: Schemas.ExternalId[];
};

export type RulesetListResponse = {
  items: Schemas.RulesetDto[];
};

export type RulesetListResponseWithCursor = {
  items: Schemas.RulesetDto[];
  nextCursor?: Schemas.NextCursorV3;
};

export type RulesetListIdsResponse = {
  /**
   * @minItems 1
   * @maxItems 100
   */
  items: Schemas.ExternalId[];
};

export type RuleListResponse = {
  items: Schemas.RuleDto[];
};

export type RuleListResponseWithCursor = {
  items: Schemas.RuleDto[];
  nextCursor?: Schemas.NextCursorV3;
};

export type RuleListIdsResponse = {
  /**
   * @minItems 1
   * @maxItems 100
   */
  items: Schemas.ExternalId[];
};

export type DataScopeListResponse = {
  items: Schemas.DataScopeDto[];
};

export type DataScopeListResponseWithCursor = {
  items: Schemas.DataScopeDto[];
  nextCursor?: Schemas.NextCursorV3;
};

export type DataScopeListIdsResponse = {
  /**
   * @minItems 1
   * @maxItems 100
   */
  items: Schemas.ExternalId[];
};
