/**
 * Generated by @openapi-codegen
 *
 * @version v1 alpha
 */
import type * as Schemas from './dataQualitySchemas';

export type ErrorResponse = {
  error: Schemas.Error;
};

export type DataSourceCollectionResponse = {
  /**
   * List of data sources
   */
  items: Schemas.DataSourceDTO[];
};

export type DataSourceCollectionResponseWithCursor = {
  /**
   * List of data sources
   */
  items: Schemas.DataSourceDTO[];
  nextCursor?: Schemas.NextCursorV3;
};

export type ListOfDataSourceIdsResponse = {
  /**
   * @minItems 1
   * @maxItems 100
   */
  items: {
    /**
     * List of data source ids for the requested item(s)
     */
    externalId: Schemas.DataSourceDTO;
  }[];
};
