/**
 * Generated by @openapi-codegen
 *
 * @version v1 alpha
 */
/**
 * @example publicdata
 */
export type Project = string;

/**
 * @default 100
 * @minimum 1
 * @maximum 1000
 */
export type Limit = number;

/**
 * @example 4zj0Vy2fo0NtNMb229mI9r1V3YG5NBL752kQz1cKtwo
 */
export type Cursor = string;
