/**
 * Generated by @openapi-codegen
 *
 * @version v1 alpha
 */
/**
 * Cognite API error.
 */
export type Error = {
  /**
   * HTTP status code.
   *
   * @format int32
   * @example 401
   */
  code: number;
  /**
   * Error message.
   *
   * @example Could not authenticate.
   */
  message: string;
};

/**
 * The number of milliseconds since 00:00:00 Thursday, 1 January 1970, Coordinated Universal Time (UTC), minus leap seconds.
 *
 * @minimum 0
 * @format int64
 */
export type EpochTimestamp = number;

/**
 * Cursor for paging through results.
 */
export type Cursor = {
  /**
   * @example 4zj0Vy2fo0NtNMb229mI9r1V3YG5NBL752kQz1cKtwo
   */
  cursor?: string;
};

export type UpsertConflict = {
  /**
   * Details about the error caused by the upsert/update.
   */
  error: {
    /**
     * The HTTP status code returned
     *
     * @format int32
     * @example 409
     */
    code: number;
    /**
     * The error message returned from the service.
     */
    message: string;
  };
};

/**
 * The cursor value used to return (paginate to) the next page of results, when more data is available.
 */
export type NextCursorV3 = string;

/**
 * @pattern ^[a-zA-Z]([a-zA-Z0-9_]{0,253}[a-zA-Z0-9])?$
 * @minLength 1
 * @maxLength 255
 */
export type DataModelId = string;

/**
 * @pattern ^[a-zA-Z]([a-zA-Z0-9_]{0,253}[a-zA-Z0-9])?$
 * @minLength 1
 * @maxLength 255
 */
export type DataModelSpace = string;

/**
 * @pattern ^[a-zA-Z0-9]([a-zA-Z0-9_-]{0,41}[a-zA-Z0-9])?$
 * @minLength 1
 * @maxLength 43
 */
export type DataModelVersion = string;

/**
 * @pattern ^[a-zA-Z]([a-zA-Z0-9_]{0,253}[a-zA-Z0-9])?$
 * @minLength 1
 * @maxLength 255
 */
export type ExternalId = string;

export type Nonce = string;

export type DataSourceDraft = {
  /**
   * Id of the data model that the data source belongs to
   *
   * @pattern ^[a-zA-Z]([a-zA-Z0-9_]{0,253}[a-zA-Z0-9])?$
   * @minLength 1
   * @maxLength 255
   */
  dataModelId: DataModelId;
  /**
   * The data model space that the data source belongs to
   *
   * @pattern ^[a-zA-Z]([a-zA-Z0-9_]{0,253}[a-zA-Z0-9])?$
   * @minLength 1
   * @maxLength 255
   */
  dataModelSpaceId: DataModelSpace;
  /**
   * The data model version that the data source belongs to
   *
   * @pattern ^[a-zA-Z0-9]([a-zA-Z0-9_-]{0,41}[a-zA-Z0-9])?$
   * @minLength 1
   * @maxLength 43
   */
  dataModelVersion: DataModelVersion;
  /**
   * External-id of the data source
   *
   * @pattern ^[a-zA-Z]([a-zA-Z0-9_]{0,253}[a-zA-Z0-9])?$
   * @minLength 1
   * @maxLength 255
   */
  externalId: ExternalId;
};

export type DataSourceDto = {
  createdTime: EpochTimestamp;
  /**
   * Id of the data model that the data source belongs to
   *
   * @pattern ^[a-zA-Z]([a-zA-Z0-9_]{0,253}[a-zA-Z0-9])?$
   * @minLength 1
   * @maxLength 255
   */
  dataModelId: DataModelId;
  /**
   * The data model space that the data source belongs to
   *
   * @pattern ^[a-zA-Z]([a-zA-Z0-9_]{0,253}[a-zA-Z0-9])?$
   * @minLength 1
   * @maxLength 255
   */
  dataModelSpaceId: DataModelSpace;
  /**
   * The data model version that the data source belongs to
   *
   * @pattern ^[a-zA-Z0-9]([a-zA-Z0-9_-]{0,41}[a-zA-Z0-9])?$
   * @minLength 1
   * @maxLength 43
   */
  dataModelVersion: DataModelVersion;
  /**
   * The external-id of the data source
   *
   * @pattern ^[a-zA-Z]([a-zA-Z0-9_]{0,253}[a-zA-Z0-9])?$
   * @minLength 1
   * @maxLength 255
   */
  externalId: ExternalId;
  lastUpdatedTime: EpochTimestamp;
};

/**
 * List of data sources to create/update
 *
 * @minItems 1
 * @maxItems 100
 */
export type DataSourceCreateRequest = {
  /**
   * @minItems 1
   * @maxItems 100
   */
  items: DataSourceDraft[];
};

export type DataSourceListIdsRequest = {
  /**
   * @minItems 1
   * @maxItems 100
   */
  items: {
    /**
     * Ids for the data sources used in the request
     */
    externalId: ExternalId;
  }[];
};

export type RulesetDraft = {
  /**
   * The description of the ruleset
   */
  description?: string;
  /**
   * The external-id of the ruleset
   *
   * @pattern ^[a-zA-Z]([a-zA-Z0-9_]{0,253}[a-zA-Z0-9])?$
   * @minLength 1
   * @maxLength 255
   */
  externalId: ExternalId;
  /**
   * The name of the ruleset
   */
  name: string;
  /**
   * The external-id of the parent ruleset
   *
   * @pattern ^[a-zA-Z]([a-zA-Z0-9_]{0,253}[a-zA-Z0-9])?$
   * @minLength 1
   * @maxLength 255
   */
  parentRulesetId?: ExternalId;
};

export type RulesetDto = {
  createdTime: EpochTimestamp;
  /**
   * The external-id of the data source
   *
   * @pattern ^[a-zA-Z]([a-zA-Z0-9_]{0,253}[a-zA-Z0-9])?$
   * @minLength 1
   * @maxLength 255
   */
  dataSourceId: ExternalId;
  /**
   * The description of the ruleset
   */
  description: string;
  /**
   * The external-id of the ruleset
   *
   * @pattern ^[a-zA-Z]([a-zA-Z0-9_]{0,253}[a-zA-Z0-9])?$
   * @minLength 1
   * @maxLength 255
   */
  externalId: ExternalId;
  /**
   * The name of the ruleset
   */
  name: string;
  lastUpdatedTime: EpochTimestamp;
  /**
   * The external-id of the parent ruleset
   *
   * @pattern ^[a-zA-Z]([a-zA-Z0-9_]{0,253}[a-zA-Z0-9])?$
   * @minLength 1
   * @maxLength 255
   */
  parentRulesetId: ExternalId;
};

/**
 * List of rulesets to create/update
 *
 * @minItems 1
 * @maxItems 100
 */
export type RulesetCreateRequest = {
  /**
   * @minItems 1
   * @maxItems 100
   */
  items: RulesetDraft[];
};

export type RulesetListIdsRequest = {
  /**
   * @minItems 1
   * @maxItems 100
   */
  items: {
    /**
     * Ids from rulesets
     */
    externalId: ExternalId;
  }[];
};

/**
 * The severity of the rule
 */
export type RuleSeverity = 'Critical' | 'High' | 'Medium' | 'Low';

export type RuleCreateDraft = {
  /**
   * Conditions used to perform validation
   */
  conditions: string;
  /**
   * External-id of the data scope connected to the rule
   *
   * @pattern ^[a-zA-Z]([a-zA-Z0-9_]{0,253}[a-zA-Z0-9])?$
   * @minLength 1
   * @maxLength 255
   */
  dataScopeId?: ExternalId;
  /**
   * The reference to a view in FDM
   */
  dataType: string;
  /**
   * The description of the rule
   */
  description?: string;
  /**
   * The error message of the rule
   */
  errorMessage?: string;
  /**
   * The external-id of the rule
   *
   * @pattern ^[a-zA-Z]([a-zA-Z0-9_]{0,253}[a-zA-Z0-9])?$
   * @minLength 1
   * @maxLength 255
   */
  externalId: ExternalId;
  /**
   * The name of the rule
   */
  name: string;
  /**
   * External-id of the ruleset connected to the rule
   *
   * @pattern ^[a-zA-Z]([a-zA-Z0-9_]{0,253}[a-zA-Z0-9])?$
   * @minLength 1
   * @maxLength 255
   */
  rulesetId?: ExternalId;
  /**
   * The severity of the rule
   */
  severity: RuleSeverity;
};

export type RuleUpdateItem = {
  /**
   * The external-id of the rule
   *
   * @pattern ^[a-zA-Z]([a-zA-Z0-9_]{0,253}[a-zA-Z0-9])?$
   * @minLength 1
   * @maxLength 255
   */
  externalId: ExternalId;
  /**
   * The properties to be updated
   */
  update: RuleUpdateDraft;
};

export type RuleUpdateDraft = {
  /**
   * Conditions used to perform validation
   */
  conditions?: string;
  /**
   * External-id of the data scope connected to the rule
   *
   * @pattern ^[a-zA-Z]([a-zA-Z0-9_]{0,253}[a-zA-Z0-9])?$
   * @minLength 1
   * @maxLength 255
   */
  dataScopeId?: ExternalId;
  /**
   * The reference to a view in FDM
   */
  dataType?: string;
  /**
   * The description of the rule
   */
  description?: string;
  /**
   * The error message of the rule
   */
  errorMessage?: string;
  /**
   * The name of the rule
   */
  name?: string;
  /**
   * External-id of the ruleset connected to the rule
   *
   * @pattern ^[a-zA-Z]([a-zA-Z0-9_]{0,253}[a-zA-Z0-9])?$
   * @minLength 1
   * @maxLength 255
   */
  rulesetId?: ExternalId;
  /**
   * The severity of the rule
   */
  severity?: RuleSeverity;
};

export type RuleDto = {
  /**
   * Conditions used to perform validation
   */
  conditions: string;
  createdTime: EpochTimestamp;
  /**
   * The external-id of the rule
   *
   * @pattern ^[a-zA-Z]([a-zA-Z0-9_]{0,253}[a-zA-Z0-9])?$
   * @minLength 1
   * @maxLength 255
   */
  externalId: ExternalId;
  /**
   * The external-id of the data scope connected to the rule
   *
   * @pattern ^[a-zA-Z]([a-zA-Z0-9_]{0,253}[a-zA-Z0-9])?$
   * @minLength 1
   * @maxLength 255
   */
  dataScopeId?: ExternalId;
  /**
   * The reference to a view in FDM
   */
  dataType: string;
  /**
   * The description of the rule
   */
  description: string;
  /**
   * The error message of the rule
   */
  errorMessage: string;
  lastUpdatedTime: EpochTimestamp;
  /**
   * The name of the rule
   */
  name: string;
  /**
   * The external-id of the ruleset connected to the rule
   *
   * @pattern ^[a-zA-Z]([a-zA-Z0-9_]{0,253}[a-zA-Z0-9])?$
   * @minLength 1
   * @maxLength 255
   */
  rulesetId?: ExternalId;
  /**
   * The severity of the rule
   */
  severity: RuleSeverity;
};

/**
 * List of rules to create
 *
 * @minItems 1
 * @maxItems 100
 */
export type RuleCreateRequest = {
  /**
   * @minItems 1
   * @maxItems 100
   */
  items: RuleCreateDraft[];
};

/**
 * List of rules to update
 *
 * @minItems 1
 * @maxItems 100
 */
export type RuleUpdateRequest = {
  /**
   * @minItems 1
   * @maxItems 100
   */
  items: RuleUpdateItem[];
};

export type RuleListIdsRequest = {
  /**
   * @minItems 1
   * @maxItems 100
   */
  items: {
    /**
     * Ids from rules
     */
    externalId: ExternalId;
  }[];
};

export type DataSourceValidationRequest = Record<string, any>;

export type DataScopeDto = {
  createdTime: EpochTimestamp;
  /**
   * The external-id of the data source
   *
   * @pattern ^[a-zA-Z]([a-zA-Z0-9_]{0,253}[a-zA-Z0-9])?$
   * @minLength 1
   * @maxLength 255
   */
  dataSourceId: ExternalId;
  /**
   * The selected data type from the data model
   */
  dataType: string;
  /**
   * The external-id of the data scope
   *
   * @pattern ^[a-zA-Z]([a-zA-Z0-9_]{0,253}[a-zA-Z0-9])?$
   * @minLength 1
   * @maxLength 255
   */
  externalId: ExternalId;
  /**
   * Filters used during validation
   */
  filters: string;
  lastUpdatedTime: EpochTimestamp;
  /**
   * The name of the data scope
   */
  name: string;
};

export type DataScopeListIdsRequest = {
  /**
   * @minItems 1
   * @maxItems 100
   */
  items: {
    /**
     * Ids from data scopes
     */
    externalId: ExternalId;
  }[];
};

/**
 * State of the rule run
 */
export type RuleRunStatus = 'Error' | 'InProgress' | 'Success';

export type RuleRunDto = {
  createdTime: EpochTimestamp;
  /**
   * The external-id of the data source
   *
   * @pattern ^[a-zA-Z]([a-zA-Z0-9_]{0,253}[a-zA-Z0-9])?$
   * @minLength 1
   * @maxLength 255
   */
  dataSourceId: ExternalId;
  /**
   * Time when the rule validation finishes
   */
  endTime: EpochTimestamp;
  /**
   * The external-id of the rule run
   *
   * @pattern ^[a-zA-Z]([a-zA-Z0-9_]{0,253}[a-zA-Z0-9])?$
   * @minLength 1
   * @maxLength 255
   */
  externalId: ExternalId;
  lastUpdatedTime: EpochTimestamp;
  /**
   * Error message in case the run failed
   */
  message: string;
  /**
   * The external-id of the related rule
   *
   * @pattern ^[a-zA-Z]([a-zA-Z0-9_]{0,253}[a-zA-Z0-9])?$
   * @minLength 1
   * @maxLength 255
   */
  ruleId: ExternalId;
  /**
   * Time when the rule validation starts
   */
  startTime: EpochTimestamp;
  status: RuleRunStatus;
};
