export const config = {
  defaultApiEndpoints: [
    'assets',
    'events',
    'datasets',
    'timeseries',
    'files',
    'templategroups',
    'templates',
  ],
  builtInTypes: {
    Asset: 'assets',
    TimeSeries: 'timeseries',
    SyntheticTimeSeries: 'timeseries',
  },
  whitelistedEndpointEndings: ['/list', '/search', '/byids'],
  ignoreUrlPatterns: [
    '/templategroups/upsert',
    '/templategroups/.*/versions/upsert',
    '/templategroups/.*/versions/.*/graphql',
    '/datamodelstorage/nodes$',
    '/schema/graphql',
    '/schema/api/.*/graphql',
    '/timeseries/data/list',
    '/files/downloadLink',
    '/files/gcs_proxy/cognitedata-file-storage/*',
  ],
  urlRewrites: {
    '/api/v1/projects/:project/*': '/$2',
    '/datamodelstorage/:resource/list': '/:resource',
    '/datamodelstorage/:resource/byids': '/:resource',
    '/datamodelstorage/:resource/search': '/:resource',
    '/datamodelstorage/:resource/delete': '/:resource',
    '/datamodelstorage/spaces': '/spaces',
    '/datamodelstorage/models': '/models',
    '/datamodelstorage/edges': '/edges',
    '/:resource/list': '/:resource',
    '/:resource/search': '/:resource',
    '/:resource/byids': '/:resource',
    '/templategroups/:templategroups_id/versions/list':
      '/templates?templategroups_id=:templategroups_id&_sort=version&_order=desc',
  },
};
