version: 2
registries:
  npm-npmjs:
    type: npm-registry
    url: https://registry.npmjs.org
    token: ${{secrets.NPM_DEPENDABOT_READONLY}}
updates:
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - 'npm-npmjs'
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "@cognite/*"
