---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: fusion-app-http-container
    service: fusion-ui
    team: cdf-ux
  name: fusion
  namespace: apps
spec:
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: fusion
    weight: 100
status: null
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"http":"fusion-backend-config"},
      "default" : "fusion-backend-config"}'
    strategy.spinnaker.io/use-source-capacity: "true"
  labels:
    app: fusion-app-http-container
    service: fusion-ui
    team: cdf-ux
  name: fusion
  namespace: apps
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: fusion
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    strategy.spinnaker.io/use-source-capacity: "true"
  labels:
    app: fusion-app-http-container
    service: fusion-ui
    team: cdf-ux
  name: fusion
  namespace: apps
spec:
  minReadySeconds: 0
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: fusion
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: fusion
        service: fusion-ui
        team: cdf-ux
    spec:
      containers:
      - image: eu.gcr.io/cognitedata/fusion-app
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 5
        name: fusion
        ports:
        - containerPort: 8000
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 8000
        resources:
          limits:
            cpu: 400m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 128Mi
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/default.conf
          name: nginx-config
          subPath: nginx.config
      volumes:
      - configMap:
          name: nginx-config-file-map
        name: nginx-config
---
apiVersion: v1
data:
  nginx.config: |+
    server {
       listen 8000;

       add_header Access-Control-Allow-Origin *;

       root /usr/share/nginx/html;
       server_tokens off;
       gzip on;
       gzip_types text/plain text/css text/xml application/xml application/javascript application/json image/svg+xml;
       gzip_comp_level 5;
       gzip_proxied any;
       gzip_vary on;

       location / {
         try_files $uri /index.html;
         add_header X-Frame-Options SAMEORIGIN always;
         add_header Cache-Control "max-age=300, stale-while-revalidate=600";
         add_header Strict-Transport-Security "max-age=63072000; includeSubdomains";
         add_header X-Content-Type-Options nosniff;
         add_header Content-Security-Policy-Report-Only "default-src 'self' https://*.preview.cogniteapp.com https://*.web.app https://*.cogniteapp.com https://storage.googleapis.com/opint-pr-server/* sentry.io; script-src 'self' https://fast.chameleon.io https://apps-cdn.cogniteapp.com/@cognite/reveal-parser-worker/ https://cdn.cogniteapp.com https://*.preview.cogniteapp.com https://*.web.app https://*.cogniteapp.com https://storage.googleapis.com/opint-pr-server/* https://cdn.jsdelivr.net/npm/monaco-editor@0.36.1/; connect-src 'self' wss: blob: data: https: https://*.preview.cogniteapp.com https://*.web.app https://*.cogniteapp.com https://storage.googleapis.com/opint-pr-server/* sentry.io; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://rsms.me/inter/inter.css https://*.preview.cogniteapp.com https://*.web.app https://*.cogniteapp.com https://storage.googleapis.com/opint-pr-server/* https://cdn.jsdelivr.net/npm/monaco-editor@0.36.1/; object-src 'none'; child-src blob: https://*.preview.cogniteapp.com https://*.web.app https://*.cogniteapp.com https://storage.googleapis.com/opint-pr-server/*; font-src 'self' data: https://fonts.gstatic.com https://rsms.me https://*.preview.cogniteapp.com https://*.web.app https://*.cogniteapp.com https://storage.googleapis.com/opint-pr-server/* https://cdn.jsdelivr.net/npm/monaco-editor@0.36.1/; worker-src 'self' blob: https://*.preview.cogniteapp.com https://*.web.app https://*.cogniteapp.com https://storage.googleapis.com/opint-pr-server/*; media-src 'self' https://*.cognitedata.com https://*.preview.cogniteapp.com https://*.web.app https://*.cogniteapp.com https://storage.googleapis.com/opint-pr-server/*; form-action https://*.preview.cogniteapp.com https://*.web.app https://*.cogniteapp.com https://storage.googleapis.com/opint-pr-server/*; img-src 'self' blob: data: https://fast.chameleon.io https://*.cognitedata.com https://auth.cognite.com https://*.preview.cogniteapp.com https://*.web.app https://*.cogniteapp.com https://storage.googleapis.com/opint-pr-server/* https://apps-cdn.cogniteapp.com; frame-src * 'self'; report-uri https://o124058.ingest.sentry.io/api/5177031/security/?sentry_key=e1b43d071a3446bfabfca7d239864bc1;";
       }

       location ~ /subapps-import-map.json$ {
         try_files /subapps-import-map-production.json =404;
         add_header Cache-Control "max-age=0, no-cache, no-store, must-revalidate";
       }

       location ~ /assets/.+\.(js|png|jpg|jpeg|map|svg|css|woff2)$ {
         expires max;
       }

       location ~ /dependencies/.+\.(js|png|jpg|jpeg|map|svg)$ {
         expires max;
       }

       location ~ \.(js|png|jpg|jpeg|map|svg)$ {
         add_header Cache-Control "max-age=300, stale-while-revalidate=3600";
       }
    }

kind: ConfigMap
metadata:
  labels:
    app: fusion-app-http-container
    service: fusion-ui
    team: cdf-ux
  name: nginx-config-file-map
  namespace: apps
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: fusion-app-http-container
    service: fusion-ui
    team: cdf-ux
  name: fusion
  namespace: apps
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fusion
