export const EMPTY_WELL_RESULT_TEXT = 'No results found';
export const LOADING_TEXT = 'Loading wellbores...';
export const NO_WELLBORES_FOUND = 'No wellbores found.';
export const WELLBORE = 'Wellbore';
export const WELL = 'Well';
export const SOURCE = 'Source'; // deprecated, use: apps/discover/src/dataLayers/wells/wells/titles.ts
export const OPERATOR = 'Operator'; // deprecated, use: apps/discover/src/dataLayers/wells/wells/titles.ts
export const WATER_DEPTH = 'Water depth'; // deprecated, use: apps/discover/src/dataLayers/wells/wells/titles.ts
export const BLOCK_NAME = 'Block name'; // deprecated, use: apps/discover/src/dataLayers/wells/wells/titles.ts
export const FIELD_NAME = 'Field name'; // deprecated, use: apps/discover/src/dataLayers/wells/wells/titles.ts
export const KB_ELEVATION = 'KB elevation';
export const NO_WELLS_AND_WELLBORE_ERROR_MESSAGE = `No wellbores are selected with wells. At least one wellbore has to be selected with a well.`;
export const FETCHING_SELECTED_WELBORE_MESSAGE =
  'Fetching selected wellbores...';
export const OPEN_FIELD_PRODUCTION_MESSAGE = 'Open field production data';
export const OPEN_BROWSER_MESSAGE = 'Open data in new browser tabs';
export const VIEW_SELECTED_WELL_TEXT = 'View the selected wells';
export const ADD_SELECTED_WELLS_TEXT = 'Add the selected wells to favorites';
export const CLEAR_SELECTION_TEXT = 'Clear selection';
export const FAVORITE_WELL_LOADING_ERROR_TEXT = 'Error loading wells';
export const FAVORITE_WELLBORE_LOADING_ERROR_TEXT = 'Error loading wellbores';
