import { ICasing } from 'SubSurface/Wells/Interfaces/ICasing';

export const bpCasings: ICasing[] = [
  {
    id: '300496757234357',
    name: 'USA0000620200_1pmrr',
    description: 'EDM Casing',
    assetId: '3449261002359307',
    externalId: 'LiYtLiMUbH_pnxnfnBvnj_1pmrr',
    metadata: {
      assy_min_inside_diameter: '2.75',
      policy_id: 'V3Kd9rrghw',
      assy_design_native_uid: '',
      assy_date_in_hole: '1336694400000000000',
      source: 'EDM',
      assy_sequence_no: '3',
      type: 'Casing',
      assy_report_desc: '36" Conductor - TIANDI',
      assy_date_landed: '1174780800000000000',
      wellboreName: 'OCS-G 09981 /GC825-6 (SP5) ST00BP00',
      assy_current_status_date: '1544486400000000000',
      assy_comments: 'LOST 118 BBLS WHILE ATTEMPTING TO CIRCULATE AT LAND OUT.',
      assy_original_md_base: '5250.999836',
      assy_current_status_reason: 'ORIGINAL INSTALL',
      object_state: 'ACTUAL',
      assy_current_status_comment:
        "INSTALLED 08/14/2014 - LPWHH AT 5022' (10' STICKUP) - SHOE AT 5338'",
      assy_current_md_top: '19511.039022',
      assy_hole_size: '26.0',
      assy_event_native_uid: '13urd',
      assy_report_type: 'CASING',
      assy_original_md_top: '4974.499836',
      assy_design_existance_kind: '',
      assy_size: '36.0',
      assy_current_md_base: '19514.06902806',
      datasetName: 'BP-EDM-casing',
      assy_current_status_desc: 'INSTALLED',
      assy_report_date: '1544486400000000000',
      assy_type: 'Casing',
      assy_native_uid: '1pmrr',
      assy_report_native_uid: 'li1tknruvq',
      parentExternalId: 'USA0000620200',
      assy_cement_jobs_native_uid: '6HFPy',
      assy_name: '36" Conductor - TIANDI',
      assy_design_name: '34576',
    },
    columns: [
      {
        name: 'comp_body_inside_diameter',
        externalId: 'comp_body_inside_diameter',
        valueType: 'DOUBLE',
        metadata: {
          unit: 'in',
        },
      },
      {
        name: 'comp_body_outside_diameter',
        externalId: 'comp_body_outside_diameter',
        valueType: 'DOUBLE',
        metadata: {
          unit: 'in',
        },
      },
      {
        name: 'comp_comment',
        externalId: 'comp_comment',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_description',
        externalId: 'comp_description',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_drift_inside_diameter',
        externalId: 'comp_drift_inside_diameter',
        valueType: 'DOUBLE',
        metadata: {
          unit: 'in',
        },
      },
      {
        name: 'comp_grade',
        externalId: 'comp_grade',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_has_threadlock',
        externalId: 'comp_has_threadlock',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_joints_no',
        externalId: 'comp_joints_no',
        valueType: 'DOUBLE',
        metadata: {},
      },
      {
        name: 'comp_length',
        externalId: 'comp_length',
        valueType: 'DOUBLE',
        metadata: {
          unit: 'ft',
        },
      },
      {
        name: 'comp_manufacturer',
        externalId: 'comp_manufacturer',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_md_base',
        externalId: 'comp_md_base',
        valueType: 'DOUBLE',
        metadata: {
          unit: 'ft',
        },
      },
      {
        name: 'comp_md_top',
        externalId: 'comp_md_top',
        valueType: 'DOUBLE',
        metadata: {
          unit: 'ft',
        },
      },
      {
        name: 'comp_model',
        externalId: 'comp_model',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_name',
        externalId: 'comp_name',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_section_type_code',
        externalId: 'comp_section_type_code',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_sequence_no',
        externalId: 'comp_sequence_no',
        valueType: 'DOUBLE',
        metadata: {},
      },
      {
        name: 'comp_serial_no',
        externalId: 'comp_serial_no',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_thread',
        externalId: 'comp_thread',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_type_code',
        externalId: 'comp_type_code',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_weight',
        externalId: 'comp_weight',
        valueType: 'DOUBLE',
        metadata: {
          unit: 'ppf',
        },
      },
    ],
    createdTime: '2020-06-19T21:19:06.981Z',
    lastUpdatedTime: '2020-07-01T07:09:30.569Z',
    dataSetId: 4464571136926873,
  },
  {
    id: '4031927249242881',
    name: 'USA0000620200_4q1d0',
    description: 'EDM Casing',
    assetId: '3449261002359307',
    externalId: 'LiYtLiMUbH_pnxnfnBvnj_4q1d0',
    metadata: {
      assy_min_inside_diameter: '12.413',
      policy_id: 'V3Kd9rrghw',
      assy_design_native_uid: '',
      assy_date_in_hole: '1540536300000000000',
      source: 'EDM',
      assy_sequence_no: '5',
      type: 'Casing',
      assy_report_desc: '22" Casing - TIANDI',
      assy_date_landed: '1174780800000000000',
      wellboreName: 'OCS-G 09981 /GC825-6 (SP5) ST00BP00',
      assy_current_status_date: '1544486400000000000',
      assy_comments: 'LOST 118 BBLS WHILE ATTEMPTING TO CIRCULATE AT LAND OUT.',
      assy_original_md_base: '7563.679836',
      assy_current_status_reason: 'ORIGINAL INSTALL',
      object_state: 'ACTUAL',
      assy_current_status_comment:
        "INSTALLED 08/14/2014 - LPWHH AT 5022' (10' STICKUP) - SHOE AT 5338'",
      assy_current_md_top: '19511.039022',
      assy_hole_size: '18.125',
      assy_event_native_uid: '13urd',
      assy_report_type: 'CASING',
      assy_original_md_top: '4970.169836',
      assy_design_existance_kind: '',
      assy_size: '22.0',
      assy_current_md_base: '19514.06902806',
      datasetName: 'BP-EDM-casing',
      assy_current_status_desc: 'INSTALLED',
      assy_report_date: '1544486400000000000',
      assy_type: 'Casing',
      assy_native_uid: '4q1d0',
      assy_report_native_uid: '10r1gef9pr',
      parentExternalId: 'USA0000620200',
      assy_cement_jobs_native_uid: '1djfb',
      assy_name: '22" Casing - TIANDI',
      assy_design_name: '34582',
    },
    columns: [
      {
        name: 'comp_body_inside_diameter',
        externalId: 'comp_body_inside_diameter',
        valueType: 'DOUBLE',
        metadata: {
          unit: 'in',
        },
      },
      {
        name: 'comp_body_outside_diameter',
        externalId: 'comp_body_outside_diameter',
        valueType: 'DOUBLE',
        metadata: {
          unit: 'in',
        },
      },
      {
        name: 'comp_comment',
        externalId: 'comp_comment',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_description',
        externalId: 'comp_description',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_drift_inside_diameter',
        externalId: 'comp_drift_inside_diameter',
        valueType: 'DOUBLE',
        metadata: {
          unit: 'in',
        },
      },
      {
        name: 'comp_grade',
        externalId: 'comp_grade',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_has_threadlock',
        externalId: 'comp_has_threadlock',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_joints_no',
        externalId: 'comp_joints_no',
        valueType: 'DOUBLE',
        metadata: {},
      },
      {
        name: 'comp_length',
        externalId: 'comp_length',
        valueType: 'DOUBLE',
        metadata: {
          unit: 'ft',
        },
      },
      {
        name: 'comp_manufacturer',
        externalId: 'comp_manufacturer',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_md_base',
        externalId: 'comp_md_base',
        valueType: 'DOUBLE',
        metadata: {
          unit: 'ft',
        },
      },
      {
        name: 'comp_md_top',
        externalId: 'comp_md_top',
        valueType: 'DOUBLE',
        metadata: {
          unit: 'ft',
        },
      },
      {
        name: 'comp_model',
        externalId: 'comp_model',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_name',
        externalId: 'comp_name',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_section_type_code',
        externalId: 'comp_section_type_code',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_sequence_no',
        externalId: 'comp_sequence_no',
        valueType: 'DOUBLE',
        metadata: {},
      },
      {
        name: 'comp_serial_no',
        externalId: 'comp_serial_no',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_thread',
        externalId: 'comp_thread',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_type_code',
        externalId: 'comp_type_code',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_weight',
        externalId: 'comp_weight',
        valueType: 'DOUBLE',
        metadata: {
          unit: 'ppf',
        },
      },
    ],
    dataSetId: 4464571136926873,
    createdTime: '2020-06-19T21:32:25.299Z',
    lastUpdatedTime: '2020-07-01T07:56:19.893Z',
  },
  {
    id: '8555307572725859',
    name: 'USA0000620200_4i6rv',
    description: 'EDM Casing',
    assetId: '3449261002359307',
    externalId: 'LiYtLiMUbH_pnxnfnBvnj_4i6rv',
    metadata: {
      assy_min_inside_diameter: '12.413',
      policy_id: 'V3Kd9rrghw',
      assy_design_native_uid: '',
      assy_date_in_hole: '1540536300000000000',
      source: 'EDM',
      assy_sequence_no: '3',
      type: 'Casing',
      assy_report_desc: '14" Casing - TIANDI',
      assy_date_landed: '1174780800000000000',
      wellboreName: 'OCS-G 09981 /GC825-6 (SP5) ST00BP00',
      assy_current_status_date: '1544486400000000000',
      assy_comments: 'LOST 118 BBLS WHILE ATTEMPTING TO CIRCULATE AT LAND OUT.',
      assy_original_md_base: '17509.999836',
      assy_current_status_reason: 'ORIGINAL INSTALL',
      object_state: 'ACTUAL',
      assy_current_status_comment:
        "INSTALLED 08/14/2014 - LPWHH AT 5022' (10' STICKUP) - SHOE AT 5338'",
      assy_current_md_top: '19511.039022',
      assy_hole_size: '18.125',
      assy_event_native_uid: '13urd',
      assy_report_type: 'CASING',
      assy_original_md_top: '4975.769836',
      assy_design_existance_kind: '',
      assy_size: '14.0',
      assy_current_md_base: '19514.06902806',
      datasetName: 'BP-EDM-casing',
      assy_current_status_desc: 'INSTALLED',
      assy_report_date: '1544486400000000000',
      assy_type: 'Casing',
      assy_native_uid: '4i6rv',
      assy_report_native_uid: '1icf5bq6e0',
      parentExternalId: 'USA0000620200',
      assy_cement_jobs_native_uid: 'qjn3s',
      assy_name: '14" Casing - TIANDI',
      assy_design_name: '34580',
    },
    columns: [
      {
        name: 'comp_body_inside_diameter',
        externalId: 'comp_body_inside_diameter',
        valueType: 'DOUBLE',
        metadata: {
          unit: 'in',
        },
      },
      {
        name: 'comp_body_outside_diameter',
        externalId: 'comp_body_outside_diameter',
        valueType: 'DOUBLE',
        metadata: {
          unit: 'in',
        },
      },
      {
        name: 'comp_comment',
        externalId: 'comp_comment',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_description',
        externalId: 'comp_description',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_drift_inside_diameter',
        externalId: 'comp_drift_inside_diameter',
        valueType: 'DOUBLE',
        metadata: {
          unit: 'in',
        },
      },
      {
        name: 'comp_grade',
        externalId: 'comp_grade',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_has_threadlock',
        externalId: 'comp_has_threadlock',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_joints_no',
        externalId: 'comp_joints_no',
        valueType: 'DOUBLE',
        metadata: {},
      },
      {
        name: 'comp_length',
        externalId: 'comp_length',
        valueType: 'DOUBLE',
        metadata: {
          unit: 'ft',
        },
      },
      {
        name: 'comp_manufacturer',
        externalId: 'comp_manufacturer',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_md_base',
        externalId: 'comp_md_base',
        valueType: 'DOUBLE',
        metadata: {
          unit: 'ft',
        },
      },
      {
        name: 'comp_md_top',
        externalId: 'comp_md_top',
        valueType: 'DOUBLE',
        metadata: {
          unit: 'ft',
        },
      },
      {
        name: 'comp_model',
        externalId: 'comp_model',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_name',
        externalId: 'comp_name',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_section_type_code',
        externalId: 'comp_section_type_code',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_sequence_no',
        externalId: 'comp_sequence_no',
        valueType: 'DOUBLE',
        metadata: {},
      },
      {
        name: 'comp_serial_no',
        externalId: 'comp_serial_no',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_thread',
        externalId: 'comp_thread',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_type_code',
        externalId: 'comp_type_code',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_weight',
        externalId: 'comp_weight',
        valueType: 'DOUBLE',
        metadata: {
          unit: 'ppf',
        },
      },
    ],
    dataSetId: 4464571136926873,
    createdTime: '2020-06-19T21:32:25.299Z',
    lastUpdatedTime: '2020-07-01T07:56:19.893Z',
  },
  {
    id: '3737284701420410',
    name: 'USA0000620200_7cqv3',
    description: 'EDM Casing',
    assetId: '3449261002359307',
    externalId: 'LiYtLiMUbH_pnxnfnBvnj_7cqv3',
    metadata: {
      assy_min_inside_diameter: '12.413',
      policy_id: 'V3Kd9rrghw',
      assy_design_native_uid: '',
      assy_date_in_hole: '1539572400000000000',
      source: 'EDM',
      assy_sequence_no: '5',
      type: 'Casing',
      assy_report_desc: '9 7/8" Liner - TIANDI',
      assy_date_landed: '1174780800000000000',
      wellboreName: 'OCS-G 09981 /GC825-6 (SP5) ST00BP00',
      assy_current_status_date: '1544486400000000000',
      assy_comments: 'LOST 118 BBLS WHILE ATTEMPTING TO CIRCULATE AT LAND OUT.',
      assy_original_md_base: '25830.999836',
      assy_current_status_reason: 'ORIGINAL INSTALL',
      object_state: 'ACTUAL',
      assy_current_status_comment:
        "INSTALLED 08/14/2014 - LPWHH AT 5022' (10' STICKUP) - SHOE AT 5338'",
      assy_current_md_top: '19511.039022',
      assy_hole_size: '26.0',
      assy_event_native_uid: '13urd',
      assy_report_type: 'CASING',
      assy_original_md_top: '16924.837836',
      assy_design_existance_kind: '',
      assy_size: '9.875',
      assy_current_md_base: '19514.06902806',
      datasetName: 'BP-EDM-casing',
      assy_current_status_desc: 'INSTALLED',
      assy_report_date: '1544486400000000000',
      assy_type: 'Casing',
      assy_native_uid: '7cqv3',
      assy_report_native_uid: '38ouavihnj',
      parentExternalId: 'USA0000620200',
      assy_cement_jobs_native_uid: '705pm,5fugf',
      assy_name: '9 7/8" Liner - TIANDI',
      assy_design_name: '34584',
    },
    columns: [
      {
        name: 'comp_body_inside_diameter',
        externalId: 'comp_body_inside_diameter',
        valueType: 'DOUBLE',
        metadata: {
          unit: 'in',
        },
      },
      {
        name: 'comp_body_outside_diameter',
        externalId: 'comp_body_outside_diameter',
        valueType: 'DOUBLE',
        metadata: {
          unit: 'in',
        },
      },
      {
        name: 'comp_comment',
        externalId: 'comp_comment',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_description',
        externalId: 'comp_description',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_drift_inside_diameter',
        externalId: 'comp_drift_inside_diameter',
        valueType: 'DOUBLE',
        metadata: {
          unit: 'in',
        },
      },
      {
        name: 'comp_grade',
        externalId: 'comp_grade',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_has_threadlock',
        externalId: 'comp_has_threadlock',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_joints_no',
        externalId: 'comp_joints_no',
        valueType: 'DOUBLE',
        metadata: {},
      },
      {
        name: 'comp_length',
        externalId: 'comp_length',
        valueType: 'DOUBLE',
        metadata: {
          unit: 'ft',
        },
      },
      {
        name: 'comp_manufacturer',
        externalId: 'comp_manufacturer',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_md_base',
        externalId: 'comp_md_base',
        valueType: 'DOUBLE',
        metadata: {
          unit: 'ft',
        },
      },
      {
        name: 'comp_md_top',
        externalId: 'comp_md_top',
        valueType: 'DOUBLE',
        metadata: {
          unit: 'ft',
        },
      },
      {
        name: 'comp_model',
        externalId: 'comp_model',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_name',
        externalId: 'comp_name',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_section_type_code',
        externalId: 'comp_section_type_code',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_sequence_no',
        externalId: 'comp_sequence_no',
        valueType: 'DOUBLE',
        metadata: {},
      },
      {
        name: 'comp_serial_no',
        externalId: 'comp_serial_no',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_thread',
        externalId: 'comp_thread',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_type_code',
        externalId: 'comp_type_code',
        valueType: 'STRING',
        metadata: {},
      },
      {
        name: 'comp_weight',
        externalId: 'comp_weight',
        valueType: 'DOUBLE',
        metadata: {
          unit: 'ppf',
        },
      },
    ],
    createdTime: '2020-06-19T21:32:25.299Z',
    lastUpdatedTime: '2020-07-01T07:56:19.893Z',
    dataSetId: 4464571136926873,
  },
];
