export const GRAPHS_DIR = './graphs';
export const DOCUMENTS_DIR = './documents';
export const DIAGRAM_PARSER_SOURCE = 'COGNITE_DIAGRAM_PARSER';
export const LINE_LABEL_PREFIX = 'LINE_LABEL_';
export const DIAGRAM_PARSER_TYPE = 'COGNITE_DIAGRAM_PARSER_TYPE';
export const DIAGRAM_PARSER_PDF_EXTERNAL_ID =
  'COGNITE_DIAGRAM_PARSER_PDF_EXTERNAL_ID';
export const DIAGRAM_PARSER_PARSED_DOCUMENT_EXTERNAL_ID =
  'COGNITE_DIAGRAM_PARSER_PARSED_DOCUMENT_EXTERNAL_ID';
