[workspace]
members = [
    "f3df",
    "i3df",
    "openctm",
    "parser-worker",
]

# [profile.release]
# This enables debug symbols - remove when actually releasing to reduce file size
# debug = true
