import { Layers } from '../types';

const MAP_DATA_URL = 'https://storage.googleapis.com/discover_layers_us/';

const weights: Record<string, number> = [
  'quadrants',
  'blocks',
  'baa',
  'licensesByOperators',
  'licenses',
  'fields',
  'fieldLabels',
  'discoveries',
  'wellheads',
].reduce((result, key, index) => {
  return {
    ...result,
    [key]: index + 1000,
  };
}, {});

const pgsMulticlientProdLayers = {
  wellheads: {
    remote: `${MAP_DATA_URL}public/NPD/wellheads.geojson`,
    name: 'Wellheads',
    color: 'black',
    defaultOn: false,
    mapLayers: [
      {
        id: 'wellheads',
        source: 'wellheads',
        type: 'circle',
        minzoom: 6,
        paint: {
          'circle-color': '#222',
          'circle-radius': 2,
          'circle-blur': 0.1,
          'circle-stroke-color': '#eee',
        },
        weight: weights.wellheads,
      },
      {
        id: 'wellheadsLabel',
        source: 'wellheads',
        type: 'symbol',
        minzoom: 7,
        layout: {
          'text-field': '{well_name}',
          'text-font': ['Open Sans Semibold', 'Arial Unicode MS Bold'],
          'text-size': 12,
          'text-offset': [0, 1],
        },
        weight: weights.wellheads,
      },
    ],
  },
  discoveries: {
    remote: `${MAP_DATA_URL}public/NPD/discoveries.geojson`,
    name: 'Discoveries',
    color: 'rgba(183, 102, 25, 0.8)',
    defaultOn: false,
    mapLayers: [
      {
        id: 'discoveries',
        source: 'discoveries',
        type: 'fill',
        layout: {},
        paint: {
          'fill-outline-color': '#000',
          'fill-color': [
            'match',
            ['get', 'Dctype'],
            'OIL',
            'rgba(71.91, 165.75, 0, 0.5)',
            'GAS',
            'rgba(255, 0, 0, 0.5)',
            'OIL/GAS',
            'rgba(178.5, 121.89, 0, 0.8)',
            'GAS/CONDENSATE',
            'rgba(255, 174.165, 0, 0.65)',
            'rgba(0, 170.085, 255, 0.875)',
          ],
        },
        weight: weights.discoveries,
      },
      {
        id: 'discoveriesLabel',
        source: 'discoveries',
        type: 'symbol',
        minzoom: 6,
        layout: {
          'text-field': '{discName}',
          'text-font': ['Open Sans Semibold', 'Arial Unicode MS Bold'],
          'text-size': 12,
        },
        weight: weights.discoveries,
      },
    ],
  },
  fields: {
    remote: `${MAP_DATA_URL}public/NPD/fields.geojson`,
    name: 'Fields',
    color: 'rgba(0, 172, 79, 0.8)',
    defaultOn: true,
    mapLayers: [
      {
        id: 'fields',
        source: 'fields',
        type: 'fill',
        layout: {},
        paint: {
          'fill-outline-color': '#000',
          'fill-color': [
            'match',
            ['get', 'Dctype'],
            'OIL',
            'rgba(71.91, 165.75, 0, 0.5)',
            'GAS',
            'rgba(255, 0, 0, 0.5)',
            'OIL/GAS',
            'rgba(178.5, 121.89, 0, 0.8)',
            'GAS/CONDENSATE',
            'rgba(255, 174.165, 0, 0.65)',
            'rgba(0, 170.085, 255, 0.875)',
          ],
        },
        weight: weights.fields,
      },
      {
        id: 'fieldsLabel',
        source: 'fields',
        type: 'symbol',
        minzoom: 6,
        layout: {
          'text-field': '{fieldName}',
          'text-font': ['Open Sans Semibold', 'Arial Unicode MS Bold'],
          'text-size': 12,
        },
        weight: weights.fieldLabels,
      },
    ],
  },
  licences: {
    remote: `${MAP_DATA_URL}public/NPD/licences.geojson`,
    name: 'Licences',
    color: 'rgba(0, 106.875, 22.275, 0.5)',
    defaultOn: true,
    mapLayers: [
      {
        id: 'licences',
        source: 'licences',
        type: 'fill',
        layout: {},
        paint: {
          'fill-outline-color': 'rgba(30, 30, 30, 1)',
          'fill-color': 'rgba(211, 211, 211, 1)',
        },
        weight: weights.licenses,
      },
      {
        id: 'licencesLabel',
        source: 'licences',
        type: 'symbol',
        minzoom: 8,
        layout: {
          'text-field': '{plName}',
          'text-font': ['Open Sans Semibold', 'Arial Unicode MS Bold'],
          'text-size': 12,
        },
        weight: weights.licenses,
      },
    ],
  },
  licensesByOperators: {
    remote: `${MAP_DATA_URL}public/NPD/licences.geojson`,
    name: 'Licenses by Operator',
    color: 'rgba(0, 106.875, 22.275, 0.5)',
    defaultOn: false,
    mapLayers: [
      {
        id: 'licensesByOperators',
        source: 'licensesByOperators',
        type: 'fill',
        layout: {},
        paint: {
          'fill-outline-color': 'rgba(0, 0, 0, 1)',
          'fill-color': [
            'match',
            ['get', 'OpLongName'],
            'Wintershall Dea Norge AS',
            'rgba(0, 255, 0, 0.75)',
            'Suncor Energy Norge AS',
            'rgba(255, 0, 0, 0.75)',
            'Wellesley Petroleum AS',
            'rgba(0, 0, 255, 0.75)',
            'DNO Norge AS',
            'rgba(0, 0, 255, 1)',
            'Equinor Energy AS',
            'rgba(248, 148, 6, 0.75)',
            'Lundin Energy Norway AS',
            'rgba(255, 182, 193, 0.75)',
            'Aker BP ASA',
            'rgba(186, 85, 211, 0.75)',
            'Neptune Energy Norge AS',
            'rgba(145, 180, 150, 0.75)',
            'OKEA ASA',
            'rgba(240, 255, 0, 1)',
            'Sval Energi AS',
            'rgba(25, 181, 254, 1)',
            'rgba(0, 106.875, 22.275, 0.5)',
          ],
        },
        weight: weights.licensesByOperators,
      },
      {
        id: 'licensesByOperatorsOpLabel',
        source: 'licensesByOperators',
        type: 'symbol',
        minzoom: 8,
        layout: {
          'text-field': '{OpLongName}',
          'text-font': ['Open Sans Semibold', 'Arial Unicode MS Bold'],
          'text-size': 12,
        },
        weight: weights.licensesByOperators,
      },
    ],
  },
  baa: {
    remote: `${MAP_DATA_URL}public/NPD/business_arrangement_areas.geojson`,
    name: 'Business Agreement Areas',
    color: 'rgba(90, 10.875, 122.275, 0.5)',
    defaultOn: false,
    mapLayers: [
      {
        id: 'baa',
        source: 'baa',
        type: 'fill',
        layout: {},
        paint: {
          'fill-outline-color': 'rgba(30, 30, 30, 1)',
          'fill-color': 'rgba(90, 10.875, 122.275, 0.5)',
        },
        weight: weights.baa,
      },
      {
        id: 'baaLabel',
        source: 'baa',
        type: 'symbol',
        minzoom: 8,
        layout: {
          'text-field': '{BsnsName}',
          'text-font': ['Open Sans Semibold', 'Arial Unicode MS Bold'],
          'text-size': 12,
        },
        weight: weights.baa,
      },
    ],
  },
  blocks: {
    remote: `${MAP_DATA_URL}public/NPD/blocks.geojson`,
    name: 'Blocks',
    color: 'transparent',
    defaultOn: true,
    alwaysOn: true,
    mapLayers: [
      {
        id: 'blocks',
        minzoom: 6,
        source: 'blocks',
        type: 'line',
        layout: {},
        paint: { 'line-color': '#fff', 'line-opacity': 0.8 },
        weight: weights.blocks,
      },
      {
        id: 'blocksLabel',
        source: 'blocks',
        type: 'symbol',
        minzoom: 6,
        maxzoom: 8,
        layout: {
          'text-field': '{block_name}',
          'text-font': ['Open Sans Semibold', 'Arial Unicode MS Bold'],
          'text-size': 10,
        },
        weight: weights.blocks,
      },
    ],
  },
  quadrants: {
    remote: `${MAP_DATA_URL}public/NPD/quadrants.geojson`,
    name: 'Quadrants',
    color: 'transparent',
    defaultOn: true,
    alwaysOn: true,
    mapLayers: [
      {
        id: 'quadrants',
        maxzoom: 6,
        source: 'quadrants',
        type: 'line',
        layout: {},
        paint: { 'line-color': '#fff', 'line-opacity': 0.8 },
        weight: weights.quadrants,
      },
    ],
  },
} as Layers;

export default pgsMulticlientProdLayers;
