export const BACKEND_SERVICE_URL_KEY = 'backendServiceBaseUrl';
export const FALLBACK_TO_FUNCTIONS_URL_KEY = 'fallbackToFunctions';
export const CLUSTER_KEY = 'cluster';
export const SEARCH_KEY = 'q';
export const TS_SEARCH_KEY = 'ts';
export const ASSET_KEY = 'asset';
export const FLOAT_NUMBER_PATTERN = /\d*\.?\d*$/;
export const CHART_POINTS_PER_SERIES = 1000;
export const RAW_DATA_POINTS_THRESHOLD = CHART_POINTS_PER_SERIES / 2;
