---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  annotations:
    external-dns.ambassador-service: ambassador-apps.apps
  labels:
    app: explorer
    team: apps
  name: explorer
spec:
  acmeProvider:
    authority: none
  ambassador_id: ambassador-apps
  hostname: explorer.app.staging.${account}.cogniteapp.com
  tlsSecret:
    name: apps-certificate-cogniteapp-com-secret
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  labels:
    app: explorer
    team: apps
  name: explorer
spec:
  add_response_headers:
    Strict-Transport-Security: max-age=31536000
  ambassador_id: ambassador-apps
  host: explorer.app.staging.${account}.cogniteapp.com
  prefix: /
  rewrite: ''
  service: explorer
  timeout_ms: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: explorer
spec:
  template:
    spec:
      containers:
        - image: eu.gcr.io/cognitedata/apps/explorer-staging
          name: explorer
          env:
            - name: URL_PREFIX
              value: explorer.app.staging.${account}
          livenessProbe:
            httpGet:
              path: /explorer/configMap.json
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /explorer/configMap.json
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 10
