version: 1
update_configs:
  # NPM deps
  - target_branch: dependency-updates
    package_manager: "javascript"
    directory: "/examples"
    ignored_updates:
      - match:
          dependency_name: "@cognite/sdk"
      - match:
          dependency_name: "@cognite/reveal"
      - match:
          dependency_name: "three"
    update_schedule: live
    automerged_updates:
      - match:
          dependency_name: "*"
          update_type: "all"

  - target_branch: dependency-updates
    package_manager: "javascript"
    directory: "/viewer"
    update_schedule: live
    automerged_updates:
      - match:
          dependency_name: "*"
          update_type: "all"

  # Rust deps
  - target_branch: dependency-updates
    package_manager: "rust:cargo"
    directory: "/f3df"
    update_schedule: live
    automerged_updates:
      - match:
          dependency_name: "*"
          update_type: "all"

  - target_branch: dependency-updates
    package_manager: rust:cargo
    directory: "/i3df"
    update_schedule: live
    automerged_updates:
      - match:
          dependency_name: "*"
          update_type: "all"

  - target_branch: dependency-updates
    package_manager: "rust:cargo"
    directory: "/viewer"
    update_schedule: live
    automerged_updates:
      - match:
          dependency_name: "*"
          update_type: "all"
