export const QUERY_KEY = {
  GET_DEVICES: () => ['GET_DEVICES'],
  GET_DEVICE_MODULES: (deviceId: string) => ['GET_DEVICE_MODULES', deviceId],
  GET_DATA_SETS: () => ['GET_DATA_SETS'],
  GET_EXTRACTORS: () => ['GET_EXTRACTORS'],
  GET_EXTRACTOR_PIPELINES: () => ['GET_EXTRACTOR_PIPELINES'],
  GET_PROJECT_CONFIG: () => ['GET_PROJECT_CONFIG'],
  GET_USER_PROFILE: () => ['GET_USER_PROFILE'],
} as const;
