import {
  DataElementType,
  DataElementUnit,
  EquipmentElementKey,
  DataElement,
} from 'scarlet/types';

export const equipmentElementsConfig: {
  [key in EquipmentElementKey]: Partial<DataElement>;
} = {
  [EquipmentElementKey.ALT_REGISTRATION_NO]: {
    label: 'Alternate Registration No.',
    type: DataElementType.INT,
    unit: undefined,
    pcmsKey: '',
  },
  [EquipmentElementKey.ASSET_NO]: {
    label: 'Asset Number',
    type: DataElementType.INT,
    unit: undefined,
    pcmsKey: '',
  },
  [EquipmentElementKey.CLASS]: {
    label: 'Class',
    type: DataElementType.STRING,
    unit: undefined,
    pcmsKey: '',
  },
  [EquipmentElementKey.COATING_SEQNO]: {
    label: 'Coating',
    type: DataElementType.STRING,
    unit: undefined,
    pcmsKey: '',
  },
  [EquipmentElementKey.CODE_STAMP_YN]: {
    label: 'Code Stamped (Y/N)',
    type: DataElementType.BOOLEAN,
    unit: undefined,
    pcmsKey: '',
  },
  [EquipmentElementKey.CUI_POTENTIAL_YN]: {
    label: 'CUI Potential',
    type: DataElementType.BOOLEAN,
    unit: undefined,
    pcmsKey: '',
  },
  [EquipmentElementKey.EQUIP_TYPE_DESCRIPTION]: {
    label: 'Equipment Description',
    type: DataElementType.STRING,
    unit: undefined,
    pcmsKey: '',
  },
  [EquipmentElementKey.DESIGN_PRESSURE]: {
    label: 'Design Pressure',
    type: DataElementType.INT,
    unit: DataElementUnit.PSI,
    pcmsKey: '',
  },
  [EquipmentElementKey.DESIGN_TEMP]: {
    label: 'Design Temperature',
    type: DataElementType.INT,
    unit: DataElementUnit.FAHRENHEIT,
    pcmsKey: '',
  },
  [EquipmentElementKey.ENVIRONMENT_SEQNO]: {
    label: 'Environment',
    unit: undefined,
    pcmsKey: '',
  },
  [EquipmentElementKey.EQUIP_HEIGHT]: {
    label: 'Equipment Height',
    type: DataElementType.FLOAT,
    unit: DataElementUnit.FEET,
    pcmsKey: '',
  },
  [EquipmentElementKey.EQUIP_LENGTH]: {
    label: 'Equipment Length',
    type: DataElementType.FLOAT,
    unit: DataElementUnit.FEET,
    pcmsKey: '',
  },
  [EquipmentElementKey.EQUIP_ID]: {
    label: 'Equipment ID',
    type: DataElementType.STRING,
    unit: undefined,
    pcmsKey: '',
  },
  [EquipmentElementKey.EQUIP_TYPE]: {
    label: 'Equipment Type',
    type: DataElementType.STRING,
    unit: undefined,
    pcmsKey: '',
  },
  [EquipmentElementKey.EQUIP_WIDTH]: {
    label: 'Equipment Width',
    type: DataElementType.FLOAT,
    unit: DataElementUnit.FEET,
    pcmsKey: '',
  },
  [EquipmentElementKey.FIREPROOFING_YN]: {
    label: 'Fireproofing',
    type: DataElementType.BOOLEAN,
    unit: undefined,
    pcmsKey: '',
  },
  [EquipmentElementKey.FULL_VACUUM_YN]: {
    label: 'Full Vacuum',
    type: DataElementType.BOOLEAN,
    unit: undefined,
    pcmsKey: '',
  },
  [EquipmentElementKey.GOVERNING_CODE]: {
    label: 'Governing Code',
    type: DataElementType.STRING,
    unit: undefined,
    pcmsKey: '',
  },
  [EquipmentElementKey.HF_ACID_SERVICE_SEQNO]: {
    label: 'HF Acid Service',
    type: DataElementType.BOOLEAN,
    unit: undefined,
    pcmsKey: '',
  },
  [EquipmentElementKey.HEAT_TRACING_YN]: {
    label: 'Heat Tracing',
    type: DataElementType.BOOLEAN,
    unit: undefined,
    pcmsKey: '',
  },
  [EquipmentElementKey.IN_SERVICE_DT]: {
    label: 'In Service Date',
    type: DataElementType.DATE,
    unit: undefined,
    pcmsKey: '',
  },
  [EquipmentElementKey.INSTALL_DT]: {
    label: 'Install Date',
    type: DataElementType.DATE,
    unit: undefined,
    pcmsKey: '',
  },
  [EquipmentElementKey.INSULATION_TYPE_SEQNO]: {
    label: 'Insulation Type',
    unit: undefined,
    pcmsKey: '',
  },
  [EquipmentElementKey.MATERIAL]: {
    label: 'General Material',
    unit: undefined,
    pcmsKey: '',
  },
  [EquipmentElementKey.MAX_ALLOW_WRK_PRES]: {
    label: 'Max allowable work pressure',
    type: DataElementType.INT,
    unit: DataElementUnit.PSI,
    pcmsKey: '',
  },
  [EquipmentElementKey.MAX_ALLOW_WRK_TEMP]: {
    label: 'Max allowable work temperature',
    type: DataElementType.INT,
    unit: DataElementUnit.FAHRENHEIT,
    pcmsKey: '',
  },
  [EquipmentElementKey.MDM_TEMP]: {
    label: 'Min. Design Metal Temp',
    type: DataElementType.INT,
    unit: DataElementUnit.FAHRENHEIT,
    pcmsKey: '',
  },
  [EquipmentElementKey.OPERATING_PRESSURE]: {
    label: 'Operating Pressure',
    type: DataElementType.INT,
    unit: DataElementUnit.PSI,
    pcmsKey: '',
  },
  [EquipmentElementKey.OPERATING_STATUS]: {
    label: 'Operating Status',
    type: DataElementType.STRING,
    unit: undefined,
    pcmsKey: '',
  },
  [EquipmentElementKey.OPERATING_TEMP]: {
    label: 'Operating Temperature',
    type: DataElementType.INT,
    unit: DataElementUnit.FAHRENHEIT,
    pcmsKey: '',
  },
  [EquipmentElementKey.ORIENTATION]: {
    label: 'Orientation',
    type: DataElementType.ORIENTATION,
    pcmsKey: '',
  },
  [EquipmentElementKey.OUTER_DIAMETER]: {
    label: 'Outer Diameter',
    type: DataElementType.FLOAT,
    unit: DataElementUnit.FEET,
    pcmsKey: '',
  },
  [EquipmentElementKey.MANUFACTURER]: {
    label: 'Manufacturer',
    type: DataElementType.STRING,
    unit: undefined,
    pcmsKey: '',
  },
  [EquipmentElementKey.P_ID_DRAWING_NO]: {
    label: 'P - ID Drawing No.',
    type: DataElementType.STRING,
    unit: undefined,
    pcmsKey: '',
  },
  [EquipmentElementKey.PROCESS_IMPACT_SEQNO]: {
    label: 'Process Impact',
    unit: undefined,
    pcmsKey: '',
  },
  [EquipmentElementKey.PWHT_YN]: {
    label: 'Post Weld Heat Treatment',
    type: DataElementType.BOOLEAN,
    unit: undefined,
    pcmsKey: '',
  },
  [EquipmentElementKey.REGISTRATION_NO]: {
    label: 'Registration No.',
    type: DataElementType.INT,
    unit: undefined,
    pcmsKey: '',
  },
  [EquipmentElementKey.RERATED_YN]: {
    label: 'Rerated',
    type: DataElementType.BOOLEAN,
    unit: undefined,
    pcmsKey: '',
  },
  [EquipmentElementKey.SERVICE]: {
    label: 'Process Service',
    unit: undefined,
    pcmsKey: '',
  },
  [EquipmentElementKey.SYSTEM]: {
    label: 'System',
    type: DataElementType.STRING,
    unit: undefined,
    pcmsKey: '',
  },
  [EquipmentElementKey.U1_ON_FILE_YN]: {
    label: 'U1 On File?',
    type: DataElementType.BOOLEAN,
    unit: undefined,
    pcmsKey: '',
  },
  [EquipmentElementKey.UNIT]: {
    label: 'Unit ID',
    type: DataElementType.STRING,
    unit: undefined,
    pcmsKey: '',
  },
};

export const equipmentElementsPriorityConfig = [
  EquipmentElementKey.UNIT,
  EquipmentElementKey.EQUIP_ID,
  EquipmentElementKey.EQUIP_TYPE_DESCRIPTION,
  EquipmentElementKey.EQUIP_TYPE,
  EquipmentElementKey.IN_SERVICE_DT,
  EquipmentElementKey.OPERATING_STATUS,
  EquipmentElementKey.ASSET_NO,
  EquipmentElementKey.GOVERNING_CODE,
  EquipmentElementKey.REGISTRATION_NO,
  EquipmentElementKey.ALT_REGISTRATION_NO,
  EquipmentElementKey.U1_ON_FILE_YN,
  EquipmentElementKey.MANUFACTURER,
  EquipmentElementKey.P_ID_DRAWING_NO,
  EquipmentElementKey.INSTALL_DT,
  EquipmentElementKey.CODE_STAMP_YN,
  EquipmentElementKey.EQUIP_LENGTH,
  EquipmentElementKey.EQUIP_WIDTH,
  EquipmentElementKey.EQUIP_HEIGHT,
  EquipmentElementKey.MAX_ALLOW_WRK_TEMP,
  EquipmentElementKey.MAX_ALLOW_WRK_PRES,
  EquipmentElementKey.MDM_TEMP,
  EquipmentElementKey.DESIGN_TEMP,
  EquipmentElementKey.DESIGN_PRESSURE,
  EquipmentElementKey.PWHT_YN,
  EquipmentElementKey.SYSTEM,
  EquipmentElementKey.CLASS,
  EquipmentElementKey.CUI_POTENTIAL_YN,
  EquipmentElementKey.SERVICE,
  EquipmentElementKey.OPERATING_TEMP,
  EquipmentElementKey.OPERATING_PRESSURE,
  EquipmentElementKey.PROCESS_IMPACT_SEQNO,
  EquipmentElementKey.MATERIAL,
  EquipmentElementKey.INSULATION_TYPE_SEQNO,
  EquipmentElementKey.COATING_SEQNO,
  EquipmentElementKey.ORIENTATION,
  EquipmentElementKey.OUTER_DIAMETER,
  EquipmentElementKey.FIREPROOFING_YN,
  EquipmentElementKey.HEAT_TRACING_YN,
  EquipmentElementKey.ENVIRONMENT_SEQNO,
  EquipmentElementKey.RERATED_YN,
  EquipmentElementKey.FULL_VACUUM_YN,
  EquipmentElementKey.HF_ACID_SERVICE_SEQNO,
];
