name: 'Get firebase project ID'
description: 'Get firebase project ID based on project config and environment'
runs:
  using: node16
  main: index.js
inputs:
  firebaseProjectId:
    description: 'firebase project ID'
    required: false
    default: 'fusion-217032465111'
  environment:
    description: 'The environment on firebase. Options: production, preview, staging'
    required: true
