name: 'Get deploy environment'
description: 'Get firebase environment where the apps needs to deploy to'
runs:
  using: node16
  main: index.js
inputs:
  project:
    description: 'NX project name'
  branch:
    description: 'Branch name where the actions is running'
