export const ColumnKeys = [
  'externalId',
  'created',
  'relation',
  'labels',
  'lastUpdatedTime',
  'parentExternalId',
  'unit',
  'id',
  'isString',
  'isStep',
  'dataSet',
  'assets',
  'type',
  'startTime',
  'endTime',
  'mimeType',
  'uploadedTime',
  'source',
  'columns',
  'asset',
  'rootAsset',
  'relationshipLabels',
] as const;
