export const configSample = {
  columns: [
    {
      property: 'productName',
      label: 'Product Name',
      optional: false,
      data_type: 'TEXT',
      default_value: '',
      exec_order: 1,
      attribute_metadata: {},
      attribute_rules: [
        {
          name: 'Matching attribute name',
          context: 'GLOBAL',
          rule_type: 'MATCHING_RULE',
          rule_value: 'Product\\sName',
        },
        {
          name: 'Matching program name',
          context: 'MEDIA_PLAN',
          rule_type: 'MATCHING_RULE',
          rule_value: 'Product\\sName',
        },
      ],
      display_order: 1,
    },
    {
      property: 'estimateName',
      label: 'Estimate Name',
      optional: false,
      data_type: 'TEXT',
      default_value: '',
      exec_order: 1,
      attribute_metadata: {},
      attribute_rules: [
        {
          name: 'Matching attribute name',
          context: 'GLOBAL',
          rule_type: 'MATCHING_RULE',
          rule_value: 'Estimate\\sName',
        },
      ],
      display_order: 1,
    },
    {
      property: 'brand',
      label: 'Brand',
      optional: true,
      data_type: 'TEXT',
      default_value: '',
      exec_order: 1,
      attribute_metadata: {},
      attribute_rules: [
        {
          name: 'Matching attribute name',
          context: 'GLOBAL',
          rule_type: 'MATCHING_RULE',
          rule_value: 'Brand',
        },
      ],
      display_order: 1,
    },
    {
      property: 'cpe',
      label: 'Client/Product/Estimate',
      optional: false,
      data_type: 'TEXT',
      default_value: '',
      exec_order: 1,
      attribute_metadata: {},
      attribute_rules: [
        {
          name: 'Matching attribute name',
          context: 'GLOBAL',
          rule_type: 'MATCHING_RULE',
          rule_value: 'Client/Product/Estimate',
        },
      ],
      display_order: 1,
    },
    {
      property: 'uploadId',
      label: 'Upload Id',
      optional: true,
      data_type: 'DECIMAL',
      default_value: '',
      exec_order: 1,
      attribute_metadata: {},
      attribute_rules: [
        {
          name: 'Matching attribute name',
          context: 'GLOBAL',
          rule_type: 'MATCHING_RULE',
          rule_value: 'Upload\\sId',
        },
      ],
      display_order: 1,
    },
    {
      property: 'ecosPbuUploadMild',
      label: 'ECOS-PBU UPLOAD MLID',
      optional: true,
      data_type: 'TEXT',
      default_value: '',
      exec_order: 1,
      attribute_metadata: {},
      attribute_rules: [
        {
          name: 'Matching attribute name',
          context: 'GLOBAL',
          rule_type: 'MATCHING_RULE',
          rule_value: 'ECOS\\-PBU\\sUPLOAD\\sMLID',
        },
        {
          name: 'Show column if campaign budet is greater then 500',
          context: 'MEDIA_PLAN',
          rule_type: 'VISIBILITY_RULE',
          rule_value: '=campaign.budget>500',
        },
        {
          name: 'Propagate value to all buylines with same order id',
          context: 'MEDIA_PLAN',
          rule_type: 'CALCULATION_RULE',
          rule_value:
            "=ctx.PROPAGATE_BUYLINE_PROPERTY(buylines, buyline,'ecosPbuUploadMild','uploadId')",
        },
      ],
      display_order: 1,
    },
    {
      property: 'referenceContract',
      label: 'REFERENCE / CONTRACT #',
      optional: true,
      data_type: 'TEXT',
      default_value: '',
      exec_order: 1,
      attribute_metadata: {},
      attribute_rules: [
        {
          name: 'Matching attribute name',
          context: 'GLOBAL',
          rule_type: 'MATCHING_RULE',
          rule_value: 'REFERENCE\\s/\\sCONTRACT\\s\\#',
        },
      ],
      display_order: 1,
    },
    {
      property: 'projectNumber',
      label: 'PROJECT #',
      optional: true,
      data_type: 'DECIMAL',
      default_value: '',
      exec_order: 1,
      attribute_metadata: {},
      attribute_rules: [
        {
          name: 'Matching attribute name',
          context: 'GLOBAL',
          rule_type: 'MATCHING_RULE',
          rule_value: 'PROJECT\\s\\#',
        },
        {
          name: 'Normalize project number',
          rule_value: '=SUBSTITUTE(buyline.projectNumber,",","")',
          rule_type: 'FORMATTING_RULE',
          context: 'GLOBAL',
        },
      ],
      display_order: 1,
    },
    {
      property: 'campaignNumber',
      label: 'CAMPAIGN #',
      optional: true,
      data_type: 'DECIMAL',
      default_value: '',
      exec_order: 1,
      attribute_metadata: {},
      attribute_rules: [
        {
          name: 'Matching attribute name',
          context: 'GLOBAL',
          rule_type: 'MATCHING_RULE',
          rule_value: 'CAMPAIGN\\s\\#',
        },
      ],
      display_order: 1,
    },
    {
      property: 'monthOfService',
      label: 'Month of Service',
      optional: true,
      data_type: 'TEXT',
      default_value: '',
      exec_order: 1,
      attribute_metadata: {},
      attribute_rules: [
        {
          name: 'Matching attribute name',
          context: 'GLOBAL',
          rule_type: 'MATCHING_RULE',
          rule_value: 'Month\\sof\\sService',
        },
      ],
      display_order: 1,
    },
    {
      property: 'market',
      label: 'Market',
      optional: true,
      data_type: 'TEXT',
      default_value: '',
      exec_order: 1,
      attribute_metadata: {},
      attribute_rules: [
        {
          name: 'Matching attribute name',
          context: 'GLOBAL',
          rule_type: 'MATCHING_RULE',
          rule_value: 'Market',
        },
      ],
      display_order: 1,
    },
    {
      property: 'campaign',
      label: 'Campaign',
      optional: true,
      data_type: 'TEXT',
      default_value: '',
      exec_order: 1,
      attribute_metadata: {},
      attribute_rules: [
        {
          name: 'Matching attribute name',
          context: 'GLOBAL',
          rule_type: 'MATCHING_RULE',
          rule_value: '^Campaign$',
        },
      ],
      display_order: 1,
    },
    {
      property: 'format',
      label: 'Format',
      optional: true,
      data_type: 'TEXT',
      default_value: '',
      exec_order: 1,
      attribute_metadata: {},
      attribute_rules: [
        {
          name: 'Matching attribute name',
          context: 'GLOBAL',
          rule_type: 'MATCHING_RULE',
          rule_value: 'Format',
        },
      ],
      display_order: 1,
    },
    {
      property: 'type',
      label: 'Type',
      optional: true,
      data_type: 'TEXT',
      default_value: '',
      exec_order: 1,
      attribute_metadata: {},
      attribute_rules: [
        {
          name: 'Matching attribute name',
          context: 'GLOBAL',
          rule_type: 'MATCHING_RULE',
          rule_value: 'Type',
        },
        {
          name: 'Format type',
          rule_value:
            '=REPLACE(buyline.type,FIND("NON-",buyline.type),LEN("NON-"),"")',
          rule_type: 'FORMATTING_RULE',
          context: 'GLOBAL',
        },
      ],
      display_order: 1,
    },
    {
      property: 'vendorPubCode',
      label: 'Vendor pub code',
      optional: true,
      data_type: 'TEXT',
      default_value: '',
      exec_order: 1,
      attribute_metadata: {},
      attribute_rules: [
        {
          name: 'Matching attribute name',
          context: 'GLOBAL',
          rule_type: 'MATCHING_RULE',
          rule_value: 'Vendor\\spub\\scode',
        },
      ],
      display_order: 1,
    },
    {
      property: 'vendor',
      label: 'Vendor',
      optional: true,
      data_type: 'TEXT',
      default_value: '',
      exec_order: 1,
      attribute_metadata: {},
      attribute_rules: [
        {
          name: 'Matching attribute name',
          context: 'GLOBAL',
          rule_type: 'MATCHING_RULE',
          rule_value: '^Vendor$',
        },
      ],
      display_order: 1,
    },
    {
      property: 'unitNumber',
      label: 'Unit No.',
      optional: true,
      data_type: 'TEXT',
      default_value: '',
      exec_order: 1,
      attribute_metadata: {},
      attribute_rules: [
        {
          name: 'Matching attribute name',
          context: 'GLOBAL',
          rule_type: 'MATCHING_RULE',
          rule_value: 'Unit\\sNo\\.',
        },
      ],
      display_order: 1,
    },
    {
      property: 'numberOfUnits',
      label: 'Number of Units',
      optional: true,
      data_type: 'DECIMAL',
      default_value: '',
      exec_order: 1,
      attribute_metadata: {},
      attribute_rules: [
        {
          name: 'Matching attribute name',
          context: 'GLOBAL',
          rule_type: 'MATCHING_RULE',
          rule_value: 'Number\\sof\\sUnits',
        },
      ],
      display_order: 1,
    },
    {
      property: 'locationDescription',
      label: 'Location Description',
      optional: true,
      data_type: 'TEXT',
      default_value: '',
      exec_order: 1,
      attribute_metadata: {},
      attribute_rules: [
        {
          name: 'Matching attribute name',
          context: 'GLOBAL',
          rule_type: 'MATCHING_RULE',
          rule_value: 'Location\\sDescription',
        },
      ],
      display_order: 1,
    },
    {
      property: 'contractedPostDate',
      label: 'Contracted Post Date',
      optional: true,
      data_type: 'DATE',
      default_value: '',
      exec_order: 1,
      attribute_metadata: {},
      attribute_rules: [
        {
          name: 'Matching attribute name',
          context: 'GLOBAL',
          rule_type: 'MATCHING_RULE',
          rule_value: 'Contracted\\sPost\\sDate',
        },
      ],
      display_order: 1,
    },
    {
      property: 'flightStartDate',
      label: 'Flight Start Date',
      optional: false,
      data_type: 'DATE',
      default_value: '',
      exec_order: 1,
      attribute_metadata: {},
      attribute_rules: [
        {
          name: 'Matching attribute name',
          context: 'GLOBAL',
          rule_type: 'MATCHING_RULE',
          rule_value: 'Flight\\sStart\\sDate',
        },
      ],
      display_order: 1,
    },
    {
      property: 'flightEndDate',
      label: 'Flight End Date',
      optional: false,
      data_type: 'DATE',
      default_value: '',
      exec_order: 1,
      attribute_metadata: {},
      attribute_rules: [
        {
          name: 'Matching attribute name',
          context: 'GLOBAL',
          rule_type: 'MATCHING_RULE',
          rule_value: 'Flight\\sEnd\\sDate',
        },
      ],
      display_order: 1,
    },
    {
      property: 'campaignDurationWeeks',
      label: 'Camapign Duration (Weeks)',
      optional: false,
      data_type: 'DECIMAL',
      default_value: '',
      exec_order: 1,
      attribute_metadata: {},
      attribute_rules: [
        {
          name: 'Matching attribute name',
          context: 'GLOBAL',
          rule_type: 'MATCHING_RULE',
          rule_value: 'Campaign\\sDuration\\s\\(Weeks\\)',
        },
      ],
      display_order: 1,
    },
    {
      property: 'campaignDurationDays',
      label: 'Camapign Duration (Days)',
      optional: false,
      data_type: 'DECIMAL',
      default_value: '',
      exec_order: 1,
      attribute_metadata: {},
      attribute_rules: [
        {
          name: 'Matching attribute name',
          context: 'GLOBAL',
          rule_type: 'MATCHING_RULE',
          rule_value: 'Campaign\\sDuration\\s\\(Days\\)',
        },
      ],
      display_order: 1,
    },
    {
      property: 'weekImpressions',
      label: '1 Week Impressions (A18+)',
      optional: true,
      data_type: 'DECIMAL',
      default_value: '',
      exec_order: 1,
      attribute_metadata: {},
      attribute_rules: [
        {
          name: 'Matching attribute name',
          context: 'GLOBAL',
          rule_type: 'MATCHING_RULE',
          rule_value: '\\d\\sWeek\\sImpressions\\s\\([a-zA-Z0-9\\+]{1,}\\)',
        },
      ],
      display_order: 1,
    },
    {
      property: 'dailyImpressions',
      label: 'Daily Impressions',
      optional: false,
      data_type: 'DECIMAL',
      default_value: '=ROUND(buyline.weekImpressions/7)',
      exec_order: 2,
      attribute_metadata: {},
      attribute_rules: [
        {
          name: 'Matching attribute name',
          context: 'GLOBAL',
          rule_type: 'MATCHING_RULE',
          rule_value: 'Daily\\sImpressions',
        },
      ],
      display_order: 1,
    },
    {
      property: 'totalContractedImpressions',
      label: 'Total Contracted Impressions',
      optional: false,
      data_type: 'DECIMAL',
      default_value: '=buyline.dailyImpressions * buyline.campaignDurationDays',
      exec_order: 3,
      attribute_metadata: {},
      attribute_rules: [
        {
          name: 'Matching attribute name',
          context: 'GLOBAL',
          rule_type: 'MATCHING_RULE',
          rule_value: 'Total\\sContracted\\sImpressions',
        },
      ],
      display_order: 1,
    },
    {
      property: 'impressionSource',
      label: 'Impression Source',
      optional: false,
      data_type: 'TEXT',
      default_value: '',
      exec_order: 1,
      attribute_metadata: {},
      attribute_rules: [
        {
          name: 'Matching attribute name',
          context: 'GLOBAL',
          rule_type: 'MATCHING_RULE',
          rule_value: 'Impression\\sSource',
        },
      ],
      display_order: 1,
    },
    {
      property: 'mediaTotal',
      label: 'Media Total',
      optional: false,
      data_type: 'CURRENCY',
      default_value: '',
      exec_order: 1,
      attribute_metadata: {},
      attribute_rules: [
        {
          name: 'Matching attribute name',
          context: 'GLOBAL',
          rule_type: 'MATCHING_RULE',
          rule_value: 'Media\\sTotal',
        },
      ],
      display_order: 1,
    },
    {
      property: 'marginFactor',
      label: 'MARGIN FACTOR',
      optional: false,
      data_type: 'DECIMAL',
      default_value: '',
      exec_order: 1,
      attribute_metadata: {},
      attribute_rules: [
        {
          name: 'Matching attribute name',
          context: 'GLOBAL',
          rule_type: 'MATCHING_RULE',
          rule_value: 'MARGIN\\sFACTOR',
        },
      ],
      display_order: 1,
    },
    {
      property: 'marginRate',
      label: 'MARGIN RATE',
      optional: false,
      data_type: 'CURRENCY',
      default_value: '',
      exec_order: 1,
      attribute_metadata: {},
      attribute_rules: [
        {
          name: 'Matching attribute name',
          context: 'GLOBAL',
          rule_type: 'MATCHING_RULE',
          rule_value: 'MARGIN\\sRATE',
        },
      ],
      display_order: 1,
    },
    {
      property: 'otherCosts',
      label: 'Production/ Install / Tax/ Other',
      optional: false,
      data_type: 'CURRENCY',
      default_value: '',
      exec_order: 1,
      attribute_metadata: {},
      attribute_rules: [
        {
          name: 'Matching attribute name',
          context: 'GLOBAL',
          rule_type: 'MATCHING_RULE',
          rule_value: 'Production\\/\\sInstall\\s/\\sTax/\\sOther',
        },
      ],
      display_order: 1,
    },
    {
      property: 'grandTotal',
      label: 'Grand Total',
      optional: false,
      data_type: 'CURRENCY',
      default_value: '=SUM(buyline.otherCosts, buyline.marginRate)',
      exec_order: 3,
      attribute_metadata: {},
      attribute_rules: [
        {
          name: 'Matching attribute name',
          context: 'GLOBAL',
          rule_type: 'MATCHING_RULE',
          rule_value: 'Grand\\sTotal',
        },
      ],
      display_order: 1,
    },
    {
      property: 'unitSize',
      label: 'UNIT SIZE',
      optional: false,
      data_type: 'TEXT',
      default_value: '',
      exec_order: 1,
      attribute_metadata: {},
      attribute_rules: [
        {
          name: 'Matching attribute name',
          context: 'GLOBAL',
          rule_type: 'MATCHING_RULE',
          rule_value: 'UNIT\\sSIZE',
        },
      ],
      display_order: 1,
    },
    {
      property: 'additionalComments',
      label: 'ADDITIONAL COMMENTS',
      optional: false,
      data_type: 'TEXT',
      default_value: '',
      exec_order: 1,
      attribute_metadata: {},
      attribute_rules: [
        {
          name: 'Matching attribute name',
          context: 'GLOBAL',
          rule_type: 'MATCHING_RULE',
          rule_value: 'ADDITIONAL\\sCOMMENTS',
        },
      ],
      display_order: 1,
    },
    {
      property: 'spotAllocations',
      label: 'Strategy',
      optional: false,
      data_type: 'DYNAMIC',
      default_value: '',
      exec_order: 1,
      attribute_metadata: {
        attributes: [
          {
            property: 'week',
            label: 'Week',
            optional: true,
            data_type: 'DATE',
            default_value: '',
            exec_order: 1,
            attribute_rules: [],
            display_order: 1,
          },
          {
            property: 'numberOfSpots',
            label: 'Number of spots',
            optional: true,
            data_type: 'NUMBER',
            default_value: '',
            exec_order: 1,
            attribute_rules: [],
            display_order: 1,
          },
          {
            property: 'weeklyCost',
            label: 'Weekly cost',
            optional: true,
            data_type: 'CURRENCY',
            default_value: '',
            exec_order: 1,
            attribute_rules: [],
            display_order: 1,
          },
        ],
      },
      attribute_rules: [
        {
          name: 'Matching attribute name',
          context: 'GLOBAL',
          rule_type: 'MATCHING_RULE',
          rule_value: 'ADDITIONAL\\sCOMMENTS',
        },
      ],
      display_order: 1,
    },
  ],
  custom_functions: [
    {
      name: 'FIRST',
      label: 'First item from list',
      body: 'return args[0]',
      return_type: 'NUMBER',
    },
    {
      name: 'SUM',
      label: 'First item from list',
      body: 'return args.reduce((sum, x) => (+sum) + (+x))',
      return_type: 'NUMBER',
    },
    {
      name: 'PROPAGATE_BUYLINE_PROPERTY',
      label:
        'Propagate value from buyline to buylines with same set of attributes',
      body: 'let buylines = args[0]; let buyline = args[1];let criteriaProperty = args[2]; let buylineProperty = args[ 3 ]; let newBuylineVal = buyline[buylineProperty ]; let searchCriteria = buyline[criteriaProperty ]; let aplicableBuylines = buylines.find(item=> item[criteriaProperty ] == searchCriteria ); aplicableBuylines.forEach(i=>i[buylineProperty ]=newBuylineVal); return aplicableBuylines.length;',
      return_type: 'NUMBER',
    },
  ],
  data_sources: [
    {
      name: 'assignCampaignsTypeDataSource',
      data_source_type: 'OBJECT_LIST',
      metadata: {
        items_label_property: 'label',
        items_value_property: 'value',
        items: [
          {
            value: 'attachNew',
            label: 'Create campaign',
          },
          {
            value: 'attachExisting',
            label: 'Attach existing',
          },
        ],
      },
    },
    {
      name: 'statusDataSource',
      data_source_type: 'LIST',
      metadata: {
        items: ['DRAFT', 'APPROVED'],
      },
    },
    {
      name: 'statusObjectsListDataSource',
      data_source_type: 'OBJECT_LIST',
      metadata: {
        items_label_property: 'name',
        items_value_property: 'id',
        items: [
          {
            id: 1,
            name: 'DRAFT',
          },
          {
            id: 2,
            name: 'APPROVED',
          },
        ],
      },
    },
    {
      name: 'Simple List data source',
      data_source_type: 'LIST',
      metadata: {
        items: ['DRAFT', 'APPROVED'],
      },
    },
    {
      name: 'Object list data source',
      data_source_type: 'OBJECT_LIST',
      metadata: {
        items_label_property: 'id',
        items_value_property: 'value',
        items: [
          {
            id: 1,
            value: 'DRAFT',
          },
          {
            id: 2,
            value: 'APPROVED',
          },
        ],
      },
    },
    {
      name: 'API list data source',
      data_source_type: 'LOOKUP',
      metadata: {
        items_label_property: 'name',
        items_value_property: 'id',
        items_lookup_api: 'https://jsonplaceholder.typicode.com/users',
      },
    },
  ],
};
