export const responseSample = [
  {
    id: 1,
    attributes: {
      clientName: 'ACME Client',
      productName: 'Starburster',
      estimateName: 'Q1_2020_OOH_Starburster',
      brand: 'Starburster Dynamite',
      cpe: 'ACM/STA/354',
      uploadId: '353545',
      ecosPbuUploadMild: '1H3HJ',
      referenceContract: '164844/1',
      projectNumber: '54321',
      campaignNumber: '615432',
      monthOfService: 'Nov-19',
      market: 'LOS ANGELES, CA',
      campaign: 'FY20 STA Dynamite OOH',
      format: 'AL:SPORT SIGNAGE',
      type: 'MEDIA',
      vendorPubCode: '40000,04',
      vendor: 'USC SPORTS PRPTY',
      unitNumber: 'USC',
      numberOfUnits: '15',
      locationDescription: 'USC SPORTS PACKAGE',
      contractedPostDate: '11/1/2015',
      flightStartDate: 'START DATE: 11/1/15',
      flightEndDate: 'END DATE: 11/30/15',
      campaignDurationWeeks: '4',
      campaignDurationDays: '29',
      weekImpressions: '',
      dailyImpressions: '',
      totalContractedImpressions: '0',
      impressionSource: '',
      mediaTotal: '25,000.00',
      marginFactor: '0.00',
      marginRate: '26,000.00',
      otherCosts: '1,000.00',
      grandTotal: '27,000.00',
      unitSize: 'VARIOUS SIZES',
      additionalComments: '',
      spotAllocations: [
        {
          week: '08/07/2019',
          numberOfSpots: '20',
          weeklyCost: '11120',
        },
        {
          week: '08/14/2019',
          numberOfSpots: '10',
          weeklyCost: '22120',
        },
      ],
    },
    created_by: 'admin',
    created_date: '2019-12-23',
    updated_date: '2019-12-23',
    updated_by: 'admin',
  },
  {
    id: 2,
    attributes: {
      clientName: 'ACME Client',
      productName: 'Starburster',
      estimateName: 'Q1_2020_OOH_Starburster',
      brand: 'Starburster Dynamite',
      cpe: 'ACM/STA/354',
      uploadId: '353546',
      ecosPbuUploadMild: '1H3E5L1',
      referenceContract: '164845/1',
      projectNumber: '54321',
      campaignNumber: '615555',
      monthOfService: 'Nov-19',
      market: 'SAN FRAN-OAK-SJ,CA',
      campaign: 'FY20 STA Dynamite OOH',
      format: 'SF:BUS SHELTER',
      type: 'MEDIA',
      vendorPubCode: '400333,02',
      vendor: 'CLEAR CHANNEL',
      unitNumber: '',
      numberOfUnits: '50',
      locationDescription: 'SAN FRANCISCO / SAN JOSE',
      contractedPostDate: '11/2/2015',
      flightStartDate: 'START DATE: 11/2/15',
      flightEndDate: 'END DATE: 11/29/15',
      campaignDurationWeeks: '4',
      campaignDurationDays: '27',
      weekImpressions: '16,920,000',
      dailyImpressions: '2,417,143',
      totalContractedImpressions: '65,262,857',
      impressionSource: 'ESTIMATED',
      mediaTotal: '49,500.00',
      marginFactor: '0.00',
      marginRate: '49,500.00',
      otherCosts: '500.00',
      grandTotal: '50,000.00',
      unitSize: 'VARIOUS SIZES',
      additionalComments: '',
      spotAllocations: [
        {
          week: '08/07/2019',
          numberOfSpots: '25',
          weeklyCost: '31120',
        },
        {
          week: '08/14/2019',
          numberOfSpots: '40',
          weeklyCost: '42120',
        },
      ],
    },
    created_by: 'admin',
    created_date: '2019-12-23',
    updated_date: '2019-12-23',
    updated_by: 'admin',
  },
  {
    id: 3,
    attributes: {
      clientName: 'ACME Client',
      productName: 'Starburster',
      estimateName: 'Q1_2020_OOH_Starburster',
      brand: 'Starburster Dynamite',
      cpe: 'ACM/STA/354',
      uploadId: '543217',
      ecosPbuUploadMild: '1H3E5L2',
      referenceContract: '164845/1',
      projectNumber: '54321',
      campaignNumber: '615555',
      monthOfService: 'Nov-19',
      market: 'SAN FRAN-OAK-SJ,CA',
      campaign: 'FY20 STA Dynamite OOH',
      format: 'O:PREMIER PANEL',
      type: 'MEDIA',
      vendorPubCode: '400333,02',
      vendor: 'CLEAR CHANNEL',
      unitNumber: '',
      numberOfUnits: '2',
      locationDescription: 'SAN FRANCISCO / SAN JOSE / OAKLAND',
      contractedPostDate: '11/2/2015',
      flightStartDate: 'START DATE: 11/2/15',
      flightEndDate: 'END DATE: 11/29/15',
      campaignDurationWeeks: '4',
      campaignDurationDays: '27',
      weekImpressions: '14,700,000',
      dailyImpressions: '2,100,000',
      totalContractedImpressions: '56,700,000',
      impressionSource: 'GEO',
      mediaTotal: '57,500.00',
      marginFactor: '0.00',
      marginRate: '60,000.00',
      otherCosts: '200.00',
      grandTotal: '60,200.00',
      unitSize: '12\'3" H X 24\'6" W',
      additionalComments: '',
      spotAllocations: [
        {
          week: '08/07/2019',
          numberOfSpots: '20',
          weeklyCost: '11120',
        },
        {
          week: '08/14/2019',
          numberOfSpots: '40',
          weeklyCost: '12120',
        },
      ],
    },
    created_by: 'admin',
    created_date: '2019-12-23',
    updated_date: '2019-12-23',
    updated_by: 'admin',
  },
  {
    id: 4,
    attributes: {
      clientName: 'ACME Client',
      productName: 'Starburster',
      estimateName: 'Q1_2020_OOH_Starburster',
      brand: 'Starburster Dynamite',
      cpe: 'ACM/STA/354',
      uploadId: '123456',
      ecosPbuUploadMild: '1H3E5L3',
      referenceContract: '164842/1',
      projectNumber: '54321',
      campaignNumber: '615555',
      monthOfService: 'Nov-19',
      market: 'LOS ANGELES, CA',
      campaign: 'FY20 STA Dynamite OOH',
      format: 'O:BULLETIN',
      type: 'MEDIA',
      vendorPubCode: '400200,01',
      vendor: 'BULLETIN DISPLAY',
      unitNumber: '108',
      numberOfUnits: '1',
      locationDescription: '108- CAHUENGA BLVD & UNIVERSAL CENTER DR W',
      contractedPostDate: '11/2/2015',
      flightStartDate: 'START DATE: 11/2/15',
      flightEndDate: 'END DATE: 11/29/15',
      campaignDurationWeeks: '4',
      campaignDurationDays: '27',
      weekImpressions: '505,564',
      dailyImpressions: '72,223',
      totalContractedImpressions: '1,950,033',
      impressionSource: 'VENDOR',
      mediaTotal: '4,000.00',
      marginFactor: '0.00',
      marginRate: '4,000.00',
      otherCosts: '20,000.00',
      grandTotal: '24,000.00',
      unitSize: "18' H X 48' W",
      additionalComments: 'INSTALLATION INCLUDED',
      spotAllocations: [
        {
          week: '08/07/2019',
          numberOfSpots: '25',
          weeklyCost: '31120',
        },
        {
          week: '08/14/2019',
          numberOfSpots: '40',
          weeklyCost: '42120',
        },
      ],
    },
    created_by: 'admin',
    created_date: '2019-12-23',
    updated_date: '2019-12-23',
    updated_by: 'admin',
  },
  {
    id: 5,
    attributes: {
      clientName: 'ACME Client',
      productName: 'Starburster',
      estimateName: 'Q1_2020_OOH_Starburster',
      brand: 'Starburster Dynamite',
      cpe: 'ACM/STA/354',
      uploadId: '353547',
      ecosPbuUploadMild: '1H3ECA1',
      referenceContract: '164842/1',
      projectNumber: '54321',
      campaignNumber: '615555',
      monthOfService: 'Nov-19',
      market: 'LOS ANGELES, CA',
      campaign: 'FY20 STA Dynamite OOH',
      format: 'O:BULLETIN',
      type: 'MEDIA',
      vendorPubCode: '400200,01',
      vendor: 'BULLETIN DISPLAY',
      unitNumber: '109',
      numberOfUnits: '1',
      locationDescription: '109- CAHUENGA BLVD & UNIVERSAL CENTER DR E',
      contractedPostDate: '11/2/2015',
      flightStartDate: 'START DATE: 11/2/15',
      flightEndDate: 'END DATE: 11/29/15',
      campaignDurationWeeks: '4',
      campaignDurationDays: '27',
      weekImpressions: '452,496',
      dailyImpressions: '64,642',
      totalContractedImpressions: '1,745,342',
      impressionSource: 'ESTIMATED',
      mediaTotal: '4,000.00',
      marginFactor: '0.00',
      marginRate: '',
      otherCosts: '0.00',
      grandTotal: '4,000.00',
      unitSize: "18' H X 48' W",
      additionalComments: '',
      spotAllocations: [
        {
          week: '08/07/2019',
          numberOfSpots: '20',
          weeklyCost: '11120',
        },
        {
          week: '08/14/2019',
          numberOfSpots: '40',
          weeklyCost: '12120',
        },
      ],
    },
    created_by: 'admin',
    created_date: '2019-12-23',
    updated_date: '2019-12-23',
    updated_by: 'admin',
  },
];
