import {
  getFields,
  getDiscoveries,
  getLicenses,
  getIdemitsuLicenses,
  getQuadrants,
  getBlocks,
  getWellbores,
  getStructuralElements,
  getFacilities,
  getPipelines,
  getWellboresExplorationActive,
  getProspects,
  getTrajectories,
  getAllBlocks,
  getAllWellbores,
} from './geospatial';
import { getMapContent } from './getMapContent';

export const mapService = {
  getMapContent,
  getFields,
  getDiscoveries,
  getLicenses,
  getIdemitsuLicenses,
  getQuadrants,
  getBlocks,
  getWellbores,
  getStructuralElements,
  getFacilities,
  getPipelines,
  getWellboresExplorationActive,
  getProspects,
  getTrajectories,
  getAllBlocks,
  getAllWellbores,
};
