export type AnnotationType =
  | 'diagrams.AssetLink'
  | 'diagrams.FileLink'
  | 'diagrams.InstanceLink'
  | 'diagrams.Junction'
  | 'diagrams.Line'
  | 'diagrams.UnhandledSymbolObject'
  | 'diagrams.UnhandledTextObject'
  | 'documents.ExtractedText'
  | 'forms.Detection'
  | 'images.AssetLink'
  | 'images.Classification'
  | 'images.InstanceLink'
  | 'images.KeypointCollection'
  | 'images.ObjectDetection'
  | 'images.TextRegion'
  | 'pointcloud.BoundingVolume';
