schema: '1'
id: 'fusion-app-prod'
pipeline:
  application: fusion-app
  name: deploy-fusion-app-prod
  template:
    source: spinnaker://deployAllClustersFromPubsub
  variables:
    service: 'fusion-app'
    pipeline: 'prod'
    githubRepository: fusion
    dockerImageName: fusion-app
    manualJudgement: true
configuration:
  description: 'Deploy fusion to fusion.cognite.com'
  inherit:
    - triggers
    - expectedArtifacts
    - notifications
