import React, { useEffect, useState } from 'react';
import { Body, Select } from '@cognite/cogs.js';
import { unwrapResult } from '@reduxjs/toolkit';
import { useDispatch } from 'react-redux';
import { AppDispatch } from 'src/store';
import { PopulateAnnotationTemplates } from 'src/store/thunks/Annotation/PopulateAnnotationTemplates';
import styled from 'styled-components';
import { Radio, RadioChangeEvent } from 'antd';
import { AnnotationFilterType, VisionFilterItemProps } from './types';

const generatedByOptions: { [key: string]: string } = {
  '': 'Both',
  context_api: 'Model',
  user: 'User',
};
const annotationStateOptions: { [key: string]: string } = {
  verified: 'True',
  rejected: 'False',
  unhandled: 'Unhandled',
};

export const AnnotationFilter = ({
  filter,
  setFilter,
}: VisionFilterItemProps) => {
  const { annotation } = filter;
  const dispatch: AppDispatch = useDispatch();

  const [annotationLabels, setAnnotationLabels] = useState<
    { value: string; label: string }[]
  >([]);

  const setAnnotationText = (newAnnotation: any) => {
    let updatedAnnotation: AnnotationFilterType | undefined = {};
    if (newAnnotation.length === 0)
      updatedAnnotation = { ...annotation, annotationText: undefined };
    if (newAnnotation.length === 1)
      updatedAnnotation = {
        ...annotation,
        annotationText: newAnnotation[0].label,
      };
    if (newAnnotation.length === 2)
      updatedAnnotation = {
        ...annotation,
        annotationText: newAnnotation[1].label,
      };

    // To clear filter
    if (
      annotation?.annotationState === undefined &&
      annotation?.generatedBy === undefined &&
      updatedAnnotation.annotationText === undefined
    )
      updatedAnnotation = undefined;

    setFilter({
      ...filter,
      annotation: updatedAnnotation,
    });
  };
  const handleAnnotationStateChange = (e: RadioChangeEvent) => {
    setFilter({
      ...filter,
      annotation: { ...annotation, annotationState: e.target.value },
    });
  };
  const handleAnnotationSourceChange = (e: RadioChangeEvent) => {
    setFilter({
      ...filter,
      annotation: { ...annotation, generatedBy: e.target.value },
    });
  };

  const getValue = (annotationText?: string) => {
    if (annotationText)
      return [{ label: annotationText, value: annotationText }];
    return [];
  };

  useEffect(() => {
    (async () => {
      const savedConfigurationsResponse = await dispatch(
        PopulateAnnotationTemplates()
      );
      const savedConfiguration = unwrapResult(savedConfigurationsResponse);
      const { predefinedKeypoints, predefinedShapes } = savedConfiguration;
      const keypointOptions = predefinedKeypoints.map((keypoint) => ({
        value: keypoint.collectionName,
        label: keypoint.collectionName,
      }));
      const shapeOptions = predefinedShapes.map((shape) => ({
        value: shape.shapeName,
        label: shape.shapeName,
      }));
      setAnnotationLabels([...keypointOptions, ...shapeOptions]);
    })();
  }, [annotation?.generatedBy]);

  return (
    <Container>
      <OptionContainer>
        <Body level={3}>Generated by</Body>
        <RadioContainer>
          {Object.keys(generatedByOptions).map((key) => (
            <Radio
              name="generatedBy"
              value={key}
              checked={annotation?.generatedBy === key}
              onChange={handleAnnotationSourceChange}
              key={key}
            >
              {' '}
              {generatedByOptions[key]}
            </Radio>
          ))}
        </RadioContainer>
      </OptionContainer>
      <OptionContainer>
        <Body level={3}>Annotation</Body>
        {/* using Multi select to enable un-select option and logically accept last option */}
        <Select
          value={getValue(annotation?.annotationText)}
          onChange={setAnnotationText}
          options={annotationLabels}
          isMulti
        />
      </OptionContainer>
      <OptionContainer>
        <Body level={3}>Annotation state</Body>
        <RadioContainer>
          {Object.keys(annotationStateOptions).map((key) => (
            <Radio
              name="annotationState"
              value={key}
              checked={annotation?.annotationState === key}
              onChange={handleAnnotationStateChange}
              key={key}
            >
              {' '}
              {annotationStateOptions[key]}
            </Radio>
          ))}
        </RadioContainer>
      </OptionContainer>
    </Container>
  );
};

const Container = styled.div`
  display: flex;
  gap: 16px;
  flex-direction: column;
`;
const OptionContainer = styled.div`
  display: flex;
  gap: 8px;
  flex-direction: column;
`;
const RadioContainer = styled.div`
  display: flex;
  gap: 8px;
`;
