name: 'Get firebase json template'
description: 'Get firebase.json content'
runs:
  using: node16
  main: index.js
inputs:
  firebaseSite:
    description: 'firebase site'
    required: true
outputs:
  content:
    description: 'the content to put in firebase.json'