import { themes } from 'prism-react-renderer';

export default {
  title: 'Reveal docs',
  tagline: '@cognite/reveal documentation site',
  url: 'https://cognitedata.github.io',
  baseUrl: '/reveal-docs/',
  favicon: 'img/favicon.ico',
  organizationName: 'cognitedata',
  projectName: 'reveal',
  clientModules: ['removeTrailingSlash.js'],
  themeConfig: {
    algolia: {
      appId: 'WK4NHSAX9S',
      apiKey: '9ba8640575bd74e729c9e6a29dfb8a78',
      indexName: 'reveal-docs',

      contextualSearch: true,
    },
    prism: {
      // changes syntax highlighting theme
      theme: themes.oceaticNext
    },
    navbar: {
      title: '@cognite/reveal',
      logo: {
        alt: 'Reveal logo',
        src: 'img/logo.svg',
        srcDark: 'img/logo_dark.svg',
      },
      items: [
        {
          type: 'docsVersionDropdown',
          position: 'left',
        },
        {
          href: 'https://github.com/cognitedata/reveal',
          label: 'GITHUB',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'light',
      copyright: `Copyright © ${new Date().getFullYear()} <a href="//cognite.com">Cognite</a>`,
    },
  },
  presets: [
    [
      '@docusaurus/preset-classic',
      {
        sitemap: {
          changefreq: 'weekly',
          priority: 0.5,
          ignorePatterns: ['/tags/**'],
          filename: 'sitemap.xml'
        },
        docs: {
          sidebarPath: require.resolve('./sidebars.js'),
          sidebarItemsGenerator: async ({ defaultSidebarItemsGenerator, ...args }) => {
            const sidebarItems = await defaultSidebarItemsGenerator(args);
            return recursiveSortByLabel(sidebarItems);
          },
          // Please change this to your repo.
          editUrl:
            'https://github.com/cognitedata/reveal/blob/master/documentation',
          remarkPlugins: [
            [require('@docusaurus/remark-plugin-npm2yarn'), { sync: true }],
            require('./src/plugins/remark-runnable-reveal-demo'),
          ],
          showLastUpdateTime: true,
          include: ['**/*.{md,mdx}'],
          exclude: [
            '**/node_modules/**/*.{md,mdx}'
          ]
        },
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      },
    ],
  ],
  plugins: [
    require.resolve('./docusaurus_plugins/docusaurusWebpack5Plugin'),
    'docusaurus-plugin-typedoc'
  ],
};

/*
* By default autogenerated sidebars are sorted alphabetically by path and filename.
* This function is used to allow items in the same folder to be sorted alphabetically by label.
*
* Documentation for sidebarItemsGenerator: https://docusaurus.io/docs/sidebar/autogenerated
*/
function recursiveSortByLabel(items) {
  const result = items.map((item) => {
    if (item.type === 'category' && item.items.length > 0) {
      return { ...item, items: recursiveSortByLabel(item.items) };
    }
    return item;
  });

  result.sort((a, b) => (a.label < b.label ? -1 : 1));
  return result;
}
