## Mark for deletion? This is identical to "platypus-e2e-tests"

name: Codecov on master
on:
  push:
    branches:
      - master
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Set NPMKEY variable
        run: |
          export NPMKEY=$(echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_READONLY_TOKEN}}")
          echo "::set-output name=NPMKEY::$NPMKEY"
        id: npm_auth_key

      - name: Create .npmrc
        run: echo '${{ steps.npm_auth_key.outputs.NPMKEY }}' > .npmrc

      - name: Install Dependency & Build
        run: |
          yarn install --frozen-lockfile
          rm .npmrc

      - name: Run unit tests
        run: |
          yarn test

      - name: Cypress run
        uses: cypress-io/github-action@v2
        # let's give this action an ID so we can refer
        # to its output values later
        id: cypress
        # Continue the build in case of an error, as we need to set the
        # commit status in the next step, both in case of success and failure
        continue-on-error: false
        env:
          NODE_ENV: mock
        # execute Cypress using a custom test command
        with:
          # let's make sure our tests pass on Chrome browser
          browser: chrome
          headless: true
          start: yarn nx serve mock-server
          wait-on: 'http://localhost:4002'
          # wait for 1 minute for the server to respond
          wait-on-timeout: 60
          # Run the cypress tests
          command: yarn nx e2e platypus-e2e

      # Disabling codecov from here, to not interfere with nx_ci
      # - name: Combine CodeCov reports
      #   run: |
      #     yarn cpdir
      #     yarn summarize-codecov

      # - name: Upload CodeCov reports
      #   uses: codecov/codecov-action@v2
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: ./coverage/coverage-final.json,./coverage/cobertura-coverage.xml,./coverage/coverage-summary.json
