name: Deploy FDX to Staging / Production
on:
  push:
    branches:
      - master

env:
  NODE_OPTIONS: '--max_old_space_size=4096'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'

      - name: Install & build 🔧
        run: yarn --network-timeout 1000000 --frozen-lockfile && npx nx build flexible-data-explorer
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_READONLY_TOKEN }}

      # Deploying to prod on master by default for now
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_HOSTING_DEPLOY_SA }}'
          channelId: live
          projectId: ${{ github.ref_name == 'master' && 'fbhosting-217032465111' || 'fbhosting-217032465111-staging' }}
          target: cognite-flexible-data-explorer-${{ github.ref_name == 'master' && 'production' || 'staging' }}
