#
# Based on this article https://medium.com/emoteev-blog/10x-faster-ci-with-nx-and-github-actions-9a51fc4e82a6
#
# Control how many jobs run in parallel by changing jobIndex: [1, 2] and jobCount: 2
# IMPORTANT - Make sure jobCount matches number of elements in jobIndex array

name: NX - CI
on:
  pull_request:

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Set NPMKEY variable
        run: |
          export NPMKEY=$(echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_READONLY_TOKEN }}")
          echo "::set-output name=NPMKEY::$NPMKEY"
        id: npm_auth_key

      - name: Create .npmrc
        run: echo '${{ steps.npm_auth_key.outputs.NPMKEY }}' > .npmrc

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

  distributed-task:
    runs-on: ubuntu-latest
    needs: install-dependencies
    strategy:
      matrix:
        target: ['test', 'lint', 'build']
        jobIndex: [1, 2, 3]
    env:
      jobCount: 3
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('yarn.lock') }}

      - name: Cache Nx
        uses: actions/cache@v3
        with:
          path: node_modules/.cache/nx
          key: cache-nx-${{ hashFiles('yarn.lock') }}-${{ matrix.target }}-${{ matrix.jobIndex }}-${{ github.sha }}
          restore-keys: |
            cache-nx-${{ hashFiles('yarn.lock') }}-${{ matrix.target }}-${{ matrix.jobIndex }}-
            cache-nx-${{ hashFiles('yarn.lock') }}-

      - run: git fetch --no-tags --prune --depth=1 origin ${{ github.base_ref }}
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: ${{ github.base_ref }}

      - name: nx run-many:${{ matrix.target }}
        id: build
        run: node ./scripts/run-many.js ${{ matrix.target }} ${{ matrix.jobIndex }} ${{ env.jobCount }} ${{ env.NX_BASE }} ${{ env.NX_HEAD }} ${{ secrets.CODECOV_TOKEN }}
        env:
          PROJECT: ${{ secrets.CLI_E2E_PROJECT }}
          TENANT: ${{ secrets.CLI_E2E_TENANT }}
          CLUSTER: ${{ secrets.CLI_E2E_CLUSTER }}
          CLIENT_ID: ${{ secrets.CLI_E2E_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLI_E2E_CLIENT_SECRET }}
          TESTING_BASE_URL: http://localhost:4002
