name: NX - CI
on:
  pull_request:
    branches-ignore:
      - release*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  NX_CLOUD_ACCESS_TOKEN: ${{secrets.NX_CLOUD_ACCESS_TOKEN}}
  NX_VERBOSE_LOGGING: true

jobs:
  setup:
    name: 'Setup'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: cache-node-modules-

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_READONLY_TOKEN }}

      - run: git fetch --no-tags --prune --depth=1 origin ${{ github.base_ref }}
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: ${{ github.base_ref }}

      - name: 'Get affected libs to build'
        id: affected-libs
        uses: './scripts/github-actions/nx-get-affected'
        with:
          base: ${{ env.NX_BASE }}
          head: ${{ env.NX_HEAD }}
          projects: 'libs/**'

      - name: 'Get affected apps to build'
        id: affected-apps
        uses: './scripts/github-actions/nx-get-affected'
        with:
          base: ${{ env.NX_BASE }}
          head: ${{ env.NX_HEAD }}
          projects: 'apps/**'
          exclude: '*shell'

      - name: 'Get affected shell apps to build'
        id: affected-shell-apps
        uses: './scripts/github-actions/nx-get-affected'
        with:
          base: ${{ env.NX_BASE }}
          head: ${{ env.NX_HEAD }}
          projects: '*shell'

      - name: 'Get affected projects for lint'
        id: affected-lint
        uses: './scripts/github-actions/nx-get-affected'
        with:
          base: ${{ env.NX_BASE }}
          head: ${{ env.NX_HEAD }}
          target: 'lint'

      - name: 'Get affected projects for test'
        id: affected-test
        uses: './scripts/github-actions/nx-get-affected'
        with:
          base: ${{ env.NX_BASE }}
          head: ${{ env.NX_HEAD }}
          target: 'test'

      - name: 'Get affected projects for e2e'
        id: affected-e2e
        uses: './scripts/github-actions/nx-get-affected'
        with:
          base: ${{ env.NX_BASE }}
          head: ${{ env.NX_HEAD }}
          target: 'e2e'

    outputs:
      affected-libs: ${{ steps.affected-libs.outputs.projects }}
      affected-libs-string: ${{ steps.affected-libs.outputs.projectsString }}
      affected-lint: ${{ steps.affected-lint.outputs.projects }}
      affected-lint-string: ${{ steps.affected-lint.outputs.projectsString }}
      affected-test: ${{ steps.affected-test.outputs.projects }}
      affected-test-string: ${{ steps.affected-test.outputs.projectsString }}
      affected-apps: ${{ steps.affected-apps.outputs.projects }}
      affected-shell-apps: ${{ steps.affected-shell-apps.outputs.projects }}
      affected-e2e: ${{ steps.affected-e2e.outputs.projects }}

  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.affected-lint != '' && toJson(fromJson(needs.setup.outputs.affected-lint)) != '[]' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('yarn.lock') }}

      - run: git fetch --no-tags --prune --depth=1 origin ${{ github.base_ref }}
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: ${{ github.base_ref }}
      - name: Lint
        env:
          NODE_OPTIONS: '--max_old_space_size=8192'
        run: npx nx run-many --target=lint --parallel --nx-bail --projects ${{ needs.setup.outputs.affected-lint-string }}

  test:
    name: 'Test'
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.affected-test != '' && toJson(fromJson(needs.setup.outputs.affected-test)) != '[]' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('yarn.lock') }}

      - run: git fetch --no-tags --prune --depth=1 origin ${{ github.base_ref }}
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: ${{ github.base_ref }}
      - name: Test
        env:
          NODE_OPTIONS: '--max_old_space_size=8192'
        run: npx nx run-many --target=test --parallel --nx-bail --projects ${{ needs.setup.outputs.affected-test-string }}

  build-libs:
    name: 'Build libs'
    runs-on: ubuntu-20.04
    needs: setup
    if: ${{ needs.setup.outputs.affected-libs != '' && toJson(fromJson(needs.setup.outputs.affected-libs)) != '[]' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('yarn.lock') }}

      - run: git fetch --no-tags --prune --depth=1 origin ${{ github.base_ref }}
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: ${{ github.base_ref }}
      - name: Build
        env:
          NODE_OPTIONS: '--max_old_space_size=8192'
        run: npx nx run-many --target=build --parallel --nx-bail --configuration=production --projects ${{ needs.setup.outputs.affected-libs-string }}

  build:
    name: Build
    runs-on: ubuntu-20.04
    needs: [setup, build-libs]
    if: ${{ !cancelled() && !failure() && needs.build-libs.result != 'failure' && needs.build-libs.result != 'cancelled' && needs.setup.outputs.affected-apps != '' && toJson(fromJson(needs.setup.outputs.affected-apps)) != '[]' }}
    strategy:
      matrix:
        project: ${{ fromJson(needs.setup.outputs.affected-apps)  }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('yarn.lock') }}

      - name: Build
        env:
          NODE_OPTIONS: '--max_old_space_size=8192'
        run: npx nx build ${{ matrix.project }} --configuration=production

  build-shell:
    name: 'Build shell apps'
    runs-on: ubuntu-20.04
    needs: [setup, build]
    if: ${{ !cancelled() && !failure() && needs.setup.outputs.affected-shell-apps != '' && toJson(fromJson(needs.setup.outputs.affected-shell-apps)) != '[]' }}
    strategy:
      matrix:
        project: ${{ fromJson(needs.setup.outputs.affected-shell-apps)  }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('yarn.lock') }}

      - name: Build
        env:
          NODE_OPTIONS: '--max_old_space_size=8192'
        run: npx nx build ${{ matrix.project }} --configuration=production
  ci-passed:
    # see https://github.community/t/status-check-for-a-matrix-jobs/127354/7
    name: CI Passed
    needs: [setup, build-libs, build, build-shell, lint, test]
    if: ${{ always() }}
    runs-on: ubuntu-20.04
    steps:
      - name: Check all job status
        # see https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#needs-context
        # see https://stackoverflow.com/a/67532120/4907315
        if: >-
          ${{
               contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
          }}
        run: exit 1
#  e2e:
#    runs-on: ubuntu-latest
#    needs: distributed-task
#    services:
#      fusion-app-test:
#        image: eu.gcr.io/cognitedata/fusion-app/dev
#        credentials:
#          username: _json_key
#          password: ${{ secrets.GCR_ACTIONS_READONLY_JSON_KEY }}
#        ports:
#          - 8080:8080
#        options: --name fusion-app-test
#    strategy:
#      matrix:
#        target: ['e2e']
#        jobIndex: [1]
#    env:
#      jobCount: 1
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#
#      - uses: actions/setup-node@v3
#        with:
#          node-version: '18'
#
#      - name: Cache node modules
#        uses: actions/cache@v3
#        with:
#          path: |
#            node_modules
#            ~/.cache/Cypress
#          key: cache-node-modules-${{ hashFiles('yarn.lock') }}
#
#      - run: git fetch --no-tags --prune --depth=1 origin ${{ github.base_ref }}
#      - name: Derive appropriate SHAs for base and head for `nx affected` commands
#        uses: nrwl/nx-set-shas@v3
#        with:
#          main-branch-name: ${{ github.base_ref }}
#
#      - name: Override nginx config
#        run: |
#          docker cp ./nginx.conf fusion-app-test:/etc/nginx/conf.d/default.conf
#          docker exec -u 0 fusion-app-test nginx -s reload
#
#      - name: Download the build folders
#        uses: actions/download-artifact@v3
#        with:
#          name: build
#          path: dist
#
#      - name: Start local HTTP server to host built apps
#        run: yarn serve dist/apps -p 3010 --cors &
#        id: serve
#
#      - name: Cypress run
#        uses: cypress-io/github-action@v4.2.2
#        id: cypress
#        continue-on-error: false
#        env:
#          PROJECT: ${{ secrets.CLI_E2E_PROJECT }}
#          TENANT: ${{ secrets.CLI_E2E_TENANT }}
#          CLUSTER: ${{ secrets.CLI_E2E_CLUSTER }}
#          CLIENT_ID: ${{ secrets.CLI_E2E_CLIENT_ID }}
#          CLIENT_SECRET: ${{ secrets.CLI_E2E_CLIENT_SECRET }}
#          DATA_EXPLORER_CLIENT_ID: ${{ secrets.DATA_EXPLORER_CLIENT_ID }}
#          DATA_EXPLORER_CLIENT_SECRET: ${{ secrets.DATA_EXPLORER_CLIENT_SECRET }}
#          TESTING_BASE_URL: http://localhost:4002
#        with:
#          command: node ./scripts/run-many.js ${{ matrix.target }} ${{ matrix.jobIndex }} ${{ env.jobCount }} ${{ env.NX_BASE }} ${{ env.NX_HEAD }} ${{ secrets.CODECOV_TOKEN }} ${{github.base_ref}}
#
#      - name: Stop HTTP server
#        if: always()
#        run: kill $(lsof -t -i :3010)

