name: Pull request title validation

on: pull_request

jobs:
  linttitle:
    name: Check if PR title follows commitlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH_TOKEN }}" > .npmrc
          yarn add @commitlint/config-conventional --frozen-lockfile
          rm .npmrc
      - name: Validate PR title
        uses: cognitedata/lint-pr-title-action@master
        with:
          configurationPath: './commitlint.config.js'
