name: preview-documentation-cleanup

# only trigger on pull request closed events both merged or not
on:
  pull_request:
    types: [ closed ]

jobs:
  build-and-deploy:
    name: Publish documentation preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Create empty folder for override
        working-directory: documentation
        run: mkdir build

      - name: Deploy empty folder to override preview
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.REVEAL_DOCS_PREVIEW_DEPLOY_KEY }}
          external_repository: cognitedata/reveal-docs-preview
          publish_branch: master
          publish_dir: documentation/build
          destination_dir: ${{ env.PR_NUMBER }}

      - name: Add comment about preview URL
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: |
            🧹 Documentation preview is deleted.
