name: Publish Package to NPM
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/cache@v3
        id: npm_cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install NPM dependencies
        if: steps.npm_cache.outputs.cache-hit != 'true'
        working-directory: viewer
        run: yarn install --immutable

      - name: Rust fmt
        working-directory: viewer
        continue-on-error: false
        run: |
            rustup component add rustfmt
            cargo fmt --check

      - name: Build production version
        working-directory: viewer
        run: yarn run build:prod

      - name: Publish to NPM
        working-directory: viewer/dist
        run: npm publish --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}