# This is a basic workflow to help you get started with Actions

name: Pull requests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-pr"
  build-pr:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: rlespinasse/github-slug-action@v3.x

      - name: Print slug variables
        run: |
          echo ${{ env.GITHUB_HEAD_REF_SLUG }}
      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('package.json') }}

      - name: Install 🔧
        run: |
          yarn install --frozen-lockfile
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Lint
        run: yarn lint

      # - name: Test
      #   run: yarn test

      # - name: Codecov
      #   uses: codecov/codecov-action@v1.0.11
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build storybook 🔧
        run: yarn build-storybook

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: storybook-static
          TARGET_FOLDER: ${{ env.GITHUB_HEAD_REF_SLUG }} # The folder the action should deploy

      - name: Comment on PR
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: 'This PR can now be previewed at the following URL: https://cognitedata.github.io/data-exploration-components/${{ env.GITHUB_HEAD_REF_SLUG }}!'
          check_for_duplicate_msg: false # OPTIONAL

      - name: Build
        run: yarn build
