name: React Components CI

on:
  pull_request:
    branches:
      - "**"

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Cognite CICD Yarn
        run: |
          echo "
          npmScopes:
            cognite:
              npmAlwaysAuth: true
              npmAuthToken: \"\${NPM_TOKEN}\"
              npmRegistryServer: "https://registry.npmjs.org"
          " >> .yarnrc.yml
        env:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Install NPM dependencies
        working-directory: react-components
        run: yarn install --immutable
        env:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Lint
        working-directory: react-components
        continue-on-error: false
        run: yarn run lint

      - name: Build components
        working-directory: react-components
        continue-on-error: false
        run: yarn run build

      - name: Build Storybook
        working-directory: react-components
        continue-on-error: false
        run: yarn run build-storybook
