name: React Components CI

on:
  pull_request:
    paths:
      - "**"
      - "!react-components/**"
    branches:
      - "**"

jobs:
  react-components-ci:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Skip due to no changes in react-components"'
