on:
  workflow_dispatch:

jobs:
  upload-parser-worker:
    name: Upload parser worker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust
        run: |
          rustup component add clippy
          rustup component add rustfmt

      - name: Build
        run: |
          # fail on warnings, test all features
          cargo fmt -- --check
          # NOTE: as of 2020-03-17, Rust 1.42, mem_replace_with_default is triggered by a macro in wasm_bindgen
          # and needs to be disabled
          # fixme: fix clippy errors and re-enable this step
          # cargo clippy --all-targets --all-features -- -D warnings -A clippy::mem_replace_with_default
          cargo test --all --verbose

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0

      - name: Install NPM dependencies
        working-directory: parser-worker
        run: yarn

      - name: Build parser-worker
        working-directory: parser-worker
        run: yarn build:prod

      - name: 🚀 Upload to cognite CDN
        working-directory: parser-worker
        env:
          APPS_CDN_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.APPS_CDN_SERVICE_ACCOUNT_CREDENTIALS }}
        run: yarn cdn-upload
