FROM node:12-alpine as build

RUN mkdir -p /home/node/testcafe/logs/
# RUN mkdir -p /home/node/node_modules/

ENV NODE_ENV production
ENV REACT_APP_E2E_MODE true
ENV REACT_APP_NOTIFICATION_DURATION 20
ENV PORT 3000
ENV HTTPS false
ENV BROWSER none

RUN apk add --no-cache  chromium --repository=http://dl-cdn.alpinelinux.org/alpine/v3.10/main

COPY ./testcafe /home/node/testcafe
COPY ./tsconfig.* /home/node/
COPY ./scripts/docker/docker-run.sh /home/node
COPY ./.testcaferc.json /home/node/.testcaferc.json

# COPY ./node_modules /home/node/node_modules

# perhaps look at manually copy some things, to avoid bundling all of node_modules: ??
# COPY ./node_modules/@testing-library /home/node/node_modules/@testing-library
# COPY ./node_modules/testcafe /home/node/node_modules/testcafe
# COPY ./node_modules/resolve-cwd /home/node/node_modules/resolve-cwd

COPY ./src /home/node/src

WORKDIR /home/node

# run the tests
CMD ["./docker-run.sh"]
